### ISSUE TITLE
[Feature Request] Long-Rest-Hit-Dice-Healing

### ISSUE THREAD

**Issue by tagnullde** [fantasycalendar/FoundryVTT-RestRecovery#10]
Since the original LRHDH Module closed up shop - some folks (me) where wondering if you would consider adding this feature to your module? ;)

**Comment by p4535992** [comment]
+1 for this

**Comment by Haxxer** [comment]
Sure! It would be good if you could list all of the features of that module in your first description, and I'll look into it sometime next year!

**Comment by tagnullde** [comment]
For sure. Thanks!

The old module (https://github.com/schultzcole/FVTT-Long-Rest-HD-Healing-5e) added the options to modify how much of the ressources a PC gets during back during a long rest. The author went further than the offical rules. 

Here are some screenshots of it's options.

![image](https://user-images.githubusercontent.com/44159008/147702695-73a967af-2ff3-47c4-aed4-c01d54830348.png)

![image](https://user-images.githubusercontent.com/44159008/147702744-65f198e3-230f-406d-a80f-ce5fb50c2bcf.png)

Once enabled you could click the long-rest button in the character sheet (it was compatible with tidy5e btw. *hint hint*) and you were promted how many hit-dice you want to roll for your healing. The other ressources were restored based on the settings as shown above.

That's basically it.
One things though - I also asked the creator of 5eHelpers if he is interested. He seemed interessted, but not so how high on his priority list it really was. Maybe it would be worthwhile to coordinate that so that none of you do double the work for no reason. ;)
 
Thank you very much for considering it. And have a happy new year!
Let's hope 2022 will get better in all aspects than the last 2 years.

**Comment by p4535992** [comment]
I just saw that @Haxxer had another project dedicated to the long rest https://github.com/Haxxer/FoundryVTT-SlowHealingLongRestSpellPoints, so this request was perhaps more correct to put it there

**Comment by Haxxer** [comment]
Nah, this is the best place. That one is not entirely RAW, it's got my own spell slot through points recovery homebrew.

**Comment by DarKDinDoN** [comment]
Hey, quick replacement for V9 while Haxxer implements the features: https://github.com/DarKDinDoN/FVTT-Long-Rest-HD-Healing-5e/releases/latest/download/module.json

⚠️ Won't maintain this.

**Comment by tagnullde** [comment]
Thank you so much! <3

**Comment by p4535992** [comment]
You did even some ui work ? god bless you!
