### ISSUE TITLE
[BUG] Short rest Warlock pact slot recovery setting is missing

### ISSUE THREAD

**Issue by SDoehren** [fantasycalendar/FoundryVTT-RestRecovery#103]
**Is your feature request related to a problem? Please describe.**
Warlock Pact Slots are inconsistently handled.  
On a long rest they follow the same rules as set for spell slots.  
On a short rest they are handled in line with base rules for pact slots (ie they refill entirely).

**Describe the solution you'd like**
Ideally a setting in both Long Rest and Short Rest to handle pact slots differently to spell slot.  
At a minimum, adding options for pact slots in the Short Rest options.

**Describe alternatives you've considered**
The only alternative I can think of is manual control.

**Additional context**
My test was to set literally every setting to "None".  
On a long rest the Warlock character would get 0 recovery, as expected.
On a short rest the Warlock would recover their slot, out of line with expectation.

**Comment by Haxxer** [comment]
This is a bug - the short rest input for the pact recovery setting was not showing up due to misconfiguration. This will be fixed in a future update:

![image](https://user-images.githubusercontent.com/12858387/194866303-bc42c539-347a-4cb9-8bf0-3b1c1632ffaa.png)

**Comment by Haxxer** [comment]
This has been fixed in the latest version
