### ISSUE TITLE
[Request] Clone Module Profiles

### ISSUE THREAD

**Issue by mnoreke** [fantasycalendar/FoundryVTT-RestRecovery#104]
**Is your feature request related to a problem? Please describe.**
I would like the ability to clone the settings for a profile so that small changes can be made between situations.

**Describe the solution you'd like**
A copy feature

**Describe alternatives you've considered**
Doing it manually

**Comment by Haxxer** [comment]
Select a profile, create a new one with that one selected. It is copied.
