### ISSUE TITLE
[Request] ShortRest / LongRest should adjust game.time

### ISSUE THREAD

**Issue by sasquach45932** [fantasycalendar/FoundryVTT-RestRecovery#105]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
1. After rest game time should be advanced by 1hr in case of short rest and by 8hrs in case of long rest. 
2. Module could check time and set/supress "Is New Day?" checkbox accordingly.

**Describe alternatives you've considered**
Manual time adjustment using other modules such as SmallTime, Simple Calendar or Macro

**Comment by sasquach45932** [comment]
Created a [pull request](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/pull/107) about it.

**Comment by Haxxer** [comment]
Added in 1.4.0, thank you for your help
