### ISSUE TITLE
[Request] More DAE Flags

### ISSUE THREAD

**Issue by rinnocenti** [fantasycalendar/FoundryVTT-RestRecovery#112]
Since you guys already entered the flags option for the DAE I have a suggestion that some items and skills can benefit from the reset module.

1 - a flag to disable need for food. for skills/potions that make the character always sustained.

**Comment by rinnocenti** [comment]
I don't know if it's possible but it has a flag that when rolling hitdice in a rest, the value always comes to the maximum in the dice.

**Comment by Haxxer** [comment]
Added in 1.4.3

Please follow the feature request template next time.
