### ISSUE TITLE
[BUG] Items with Custom Recovery per Day do not recharge with Simple Calendar enabled.

### ISSUE THREAD

**Issue by M0nk3yy** [fantasycalendar/FoundryVTT-RestRecovery#115]
**The Bug**
This test item does nothing but is set to recover 1d6 uses per day (i.e. new day).

![image](https://user-images.githubusercontent.com/66137312/208421445-f7e5ed02-0498-4db1-8921-0b5b299c3f02.png)

With SC enabled in testing, the only way to get a "new day" is to repeatedly use the GM Prompt Rest until new days are given. Even when the new day prompt is given, no charges are recovered.

GM Prompt:

![image](https://user-images.githubusercontent.com/66137312/208421764-623c2233-4f5b-4555-8c80-64403e29ee96.png)

Resultant player window: 

![image](https://user-images.githubusercontent.com/66137312/208421843-a673fcdc-e813-4bb5-8ea3-8101d47e95bb.png)

Result with no charges:

![image](https://user-images.githubusercontent.com/66137312/208421894-8aaf247c-856a-4122-98e4-68972f104b77.png)

Same process WITHOUT Simple Calendar enabled:

![image](https://user-images.githubusercontent.com/66137312/208422245-5177292f-7b84-42a1-aab3-a9e4e5b166a7.png)
![image](https://user-images.githubusercontent.com/66137312/208422292-02374fee-3a62-4dd9-a203-064ba9b25999.png)
![image](https://user-images.githubusercontent.com/66137312/208422354-55549980-9bc4-49ff-9b62-fbc469c645c2.png)

As a side note, the player-side "is new day" should probably ticked by default if the GM has selected new day.

**Setup:**
![image](https://user-images.githubusercontent.com/66137312/208421950-42d8f4a4-1277-43b9-beb4-ebc1603cfabd.png)

**Active modules:**
 - Rest Recovery
 - libwrapper
 - Simple Calendar

**Comment by M0nk3yy** [comment]
Yeah, that element is my bad. I am not used to using simple calendar other than having it run in the background tbh.

**Comment by Haxxer** [comment]
This has been fixed in 1.4.4, as you can now disable the SC integration if you so wish
