### ISSUE TITLE
[Request] Retain ability to manually set "is new day"

### ISSUE THREAD

**Issue by M0nk3yy** [fantasycalendar/FoundryVTT-RestRecovery#116]
Currently when Simple Calendar is active, neither players nor GMs can choose to do a "new day" long rest. It is calcualted automatically. This requires the GM to ensure the date and time is up to date. Generally I do not use Simple Calendar to accurately track the time, just as a calendar of major events and time tracking for effects, so this adds extra burden, and a task to remember.

Additionally, the scenario where I encountered the issue, was that I was trying to apply Long Rests as a GM out of game. With this automated setting, the only way to do so, is to open a browser and log in as a player which (in my opinion) is a needless complication.

Ideally, I think the preferred solution would be to keep the default "new day?" prompts for both GMs (in the Prompt Rest dialog) and for Players resting manually, with the automation as an optional setting.

**Comment by Haxxer** [comment]
Added in 1.4.4
