### ISSUE TITLE
[Request] Optional homebrew rule: No consume half unit

### ISSUE THREAD

**Issue by marceloabner** [fantasycalendar/FoundryVTT-RestRecovery#118]
**Describe the solution you'd like**
Just having an optional rule disabling half-unit consumption.

**Additional context**
This option opens the possibility for some custom homebrew rules without the hassling of using half quantities of food.

**Comment by Haxxer** [comment]
@marceloabner was this closed in error?

**Comment by marceloabner** [comment]
No. I just misunderstood the feature _"one charge worth entire day worth"_ on the item menu, which is just what I was asking about in this feature request. Sorry.
