### ISSUE TITLE
[BUG] RR is no longer applying DFreds Exhaustion

### ISSUE THREAD

**Issue by LukasPrism** [fantasycalendar/FoundryVTT-RestRecovery#119]
Rest Recovery is no longer applying the Convenient Effects exhaustion when players don’t eat/drink during long rests

1. Select CE in settings for exhaustion
2. Long rest, don’t eat anything 
3. Observe exhaustion on character sheet but not the CE applied to the players

Have tested with only CE and RR (and dependencies) activated.

**Comment by dczwardCZAR** [comment]
I can confirm this bug - same happens for me.

**Comment by Haxxer** [comment]
Fixed in 1.4.5
