### ISSUE TITLE
[Request] Min & Max Hit Dice rolls for long rest + amount of recovered hit dice on long rest

### ISSUE THREAD

**Issue by diwako** [fantasycalendar/FoundryVTT-RestRecovery#120]
**Is your feature request related to a problem? Please describe.**
Currently playing a game with a homebrew rule for long rests which dictates how many hit dice rolls a player can do on a long rest.
The rule is as minimum of 0 rolls and max of half of level rolls on hit dice
Furthermore a rule how many hit dice are being recovered. If you use hit dice during long rest you do not recover any.

**Describe the solution you'd like**
My GM has noticed that similar min and mox options are avaiable for short rests. The same system for long rests would suffice for the first point.
For the second point an optional checkbox (default checked for default behaviour) on the long rest dialog if hit dice should be recovered with this rest or not.

**Describe alternatives you've considered**
Workaround, kind of, is to just use short rests, and then directly after that do a long rest, however the hit dice will be auto recovered in that case and need manualy editing.

**Comment by Haxxer** [comment]
I don't quite understand how you can play with minimum of 0 rolls, but also if you roll you regain no hit dice? So you never recover any hit dice?

**Comment by Haxxer** [comment]
Added in 1.4.6

**Comment by diwako** [comment]
Regardless, thank you for implementing these things. I will let my GM know.

**Comment by Haxxer** [comment]
I didn't implement min spend on long rests because I couldn't see how to implement it properly, so maybe in the future if there's a need for it I can review it

**Comment by diwako** [comment]
I will let you know if this is sufficient or not. The 0 rolls was more of a floor value that as player can choos not to roll any dice more than anthing.

**Comment by diwako** [comment]
Just heard back from my GM, they are very delighted and told me this works very well.
