### ISSUE TITLE
[BUG] Configure Resource Recovery button fails

### ISSUE THREAD

**Issue by V3rotti** [fantasycalendar/FoundryVTT-RestRecovery#121]
**Describe the bug**
The Button in the Character-Sheet seems to fail.
This Error is shown in the console.

**To Reproduce**
1. Open Charactersheet
2. Click on "Configure Resource Recovery"

**Expected behavior**
Resource Recovery Options are shown to configure

**Screenshots**
![image](https://user-images.githubusercontent.com/56869989/210205720-69f61b49-2331-4e98-9403-0996423d5f39.png)

**Setup:**
 - Foundry Version: V10.290
 - System Version: DND5e 2.0.3
 - Rest Recovery Version: 1.4.5
 - Browser & version Google Chrome  108.0.5359.125

**Active modules:**
 - Rest Recovery
 - libwrapper
 - tidy5e Sheet

**Additional context**

**Comment by Haxxer** [comment]
Fixed in 1.4.6
