### ISSUE TITLE
Add other options to propmpt

### ISSUE THREAD

**Issue by BladeFireLight** [fantasycalendar/FoundryVTT-RestRecovery#122]
I use the taskbar mod because the user list starts covering up buttons added by other mods I use. 
the taskbar's user list does not work with the request rest button. 

Can a method (or documentation) be added to allow the request UI to launch via Macro. or add a different UI button to trigger that is not part of the user list.

**Comment by Haxxer** [comment]
Sure, here go you:

```js
game.restrecovery.renderPromptRestInterface();
```

https://github.com/fantasycalendar/FoundryVTT-RestRecovery/blob/main/scripts/api.js#L13-L16
