### ISSUE TITLE
Slow Natural Healing

### ISSUE THREAD

**Issue by arcanjl** [fantasycalendar/FoundryVTT-RestRecovery#125]
This Module does everything I could think of, so imagine my surprise when I couldn't find the "Slow Natural Healing" variant. Am I missing it? I hope so, cause I would love to use this mod. :)

**Comment by Haxxer** [comment]
Have you checked the long rest settings?

**Comment by arcanjl** [comment]
Yes, many times. I feel that it should be there, but I just can't find it

**Comment by Haxxer** [comment]
Roll Hit Dice On Long Rest
+
HP recovery on long rest set to none

**Comment by arcanjl** [comment]
TY! My brain could not get bast looking for "Slow or Natural"
