### ISSUE TITLE
[Request] Add Special Handling for Power Surge

### ISSUE THREAD

**Issue by MaxPat931** [fantasycalendar/FoundryVTT-RestRecovery#126]
**Is your feature request related to a problem? Please describe.**
A War Wizard's Power Surge feature has a weird recharge mechanic I don't think I can currently handle. On a rest, if the feature has 0 remaining uses, the character gains 1 use, otherwise retain the current number of uses

**Describe the solution you'd like**
Add Power Surge to the Feature Names tab, which will allow for the module to address the recharge mechanic

**Describe alternatives you've considered**
Manual

**Comment by Haxxer** [comment]
`Whenever you finish a long rest, your number of power surges resets to one.`

It seems you do not keep them?

**Comment by MaxPat931** [comment]
Ah, you are right on a LR it resets to 1 always, on a SR it retains the number of charges unless you have none then it resets to 1

**Comment by MaxPat931** [comment]
Thank you!
