### ISSUE TITLE
[Request] Shrink space on modified character Sheets

### ISSUE THREAD

**Issue by KJTailor** [fantasycalendar/FoundryVTT-RestRecovery#128]
I have a character sheet module running that lets character sheets look more like DnDBeyond sheets (https://github.com/FreddyEs/mybeyond-theme). The issue, your Rest Recovery Module looks like this:
![image](https://user-images.githubusercontent.com/87787745/216799123-61c95974-3fc6-400b-82f9-a84e00e201e3.png)

I know it's more tidy on the regular character sheets, but I was hoping this might be something to take up with you? Ideally change the space "Configure Resource Recovery" takes up, if that is possible?

Thanks

**Comment by Haxxer** [comment]
I am not able to install this on v10 - do you have a manifest link I can use?

**Comment by KJTailor** [comment]
try this :)

[manifest link](https://fvtt-modules.eschmann.online/mybeyond-theme/module.json)

**Comment by Padhiver** [comment]
Hi!
Just to warn you, it happens also on the core sheet when you enlarge it.
