### ISSUE TITLE
Smaller space on prompt window, elements hidden

### ISSUE THREAD

**Issue by stickas** [fantasycalendar/FoundryVTT-RestRecovery#130]
![image (1)](https://user-images.githubusercontent.com/41856855/216851972-348ead16-3275-4775-84e4-3d1e49de7de7.png)
First of all, some of the elements of the prompt window are lost the moment you select one character for the rest, as they are pushed to the right, outside of the space of the prompt window but some still clickable.
Secondly, sometimes the mod has autopicked some of the actors in my world (all owned by players but not the active ones that are logged in and appear in the scene),
Last, without the simple calendar integration enabled, I can only pick only one character and everything is pushed to the right outside of click range.

No Simple Calendar Integration
![image (2)](https://user-images.githubusercontent.com/41856855/216851995-33c37b94-5230-4cff-9b0b-62743157419e.png)
With Simple Calendar integration
![image](https://user-images.githubusercontent.com/41856855/216851997-ef40e2a2-1cef-4dd8-847d-a7ea7fb5b760.png)

**Setup:**
 - Foundry (client) Version: 10.291
 - System Version: DND5e 2.1.4
 - Rest Recovery Version: [e.g. 1.0.0]

**Active modules:**
 - Rest Recovery
 - libwrapper

Simple Calendar is set to not be automated. I only use it for manually set the dates and for notes only.
The weirdest thing is that I created a new world again with only those 2 mods and it works properly. Same settings, same everything, no problem.

Edit: There was an issue with the previous DND5e System Version which messed up every custom sheet for actors. This version reverted it. Maybe it has something to do with that.

**Comment by Haxxer** [comment]
Hopefully fixed in 1.4.8, reopen if it still happens
