### ISSUE TITLE
[BUG] Hit dice max buffer not working

### ISSUE THREAD

**Issue by verticalmike** [fantasycalendar/FoundryVTT-RestRecovery#131]
**Describe the bug**
When using the Enable hit dice max buffer option, hit dice on long rest do not temporarily exceed the maximum.

**To Reproduce**
Created a new world using DnD5e, the only modules installed are libWrapper and Rest Recovery for 5e

Using the following options
- Enable long rest hit dice rolls
- Enable hit dice recovery before finishing long rest
- Enable  hit dice max buffer
- Hit points recovery fraction set to none
All other options are set to the default

Using a character with maximum hit dice, and a non-maximum hit point count press the long rest button
Press Begin long Rest
Hit dice do not exceed the maximum for the purpose of being used during a long rest.

**Expected behavior**
Hit dice exceed the maximum so they may be rolled during a long rest. 

**Screenshots**

**Setup:**
 - Foundry Version 10 Build 291
 - System Version: DnD5e - Fifth Edition System 2.1.4
 - Rest Recovery Version:  1.4.7
 - Browser & version: Google Chrome 109.0.5414.120 

**Active modules:**
 - Rest Recovery
 - libwrapper

**Additional context**

**Comment by Haxxer** [comment]
This is because of DnD5e's new forceful validation. I can't set the hit dice left over to a negative value. I will find a different way around.

**Comment by Haxxer** [comment]
Fixed in 1.4.8
