### ISSUE TITLE
[BUG] Module Shows in Systems Outside of 5e

### ISSUE THREAD

**Issue by Vhostym-the-Sojourner** [fantasycalendar/FoundryVTT-RestRecovery#133]
**Describe the bug**
The module shows for other systems outside of 5e. Can the manifest be updated to be restricted to the compatible system?

Steps to Reproduce

    Go to Module Management in a non-5e system
    The module displays

Versions

    Module: [1.4.8]
    Foundry: [10.291]

**Comment by Haxxer** [comment]
I would have thought this would sort it out:

https://github.com/fantasycalendar/FoundryVTT-RestRecovery/blob/main/module.json#L39-L40

I suppose that's not the case.

**Comment by Haxxer** [comment]
I see, I have now fixed it. It will be included in the next update.

**Comment by Vhostym-the-Sojourner** [comment]
Awesome, thank you! Sorry, only just now seeing this. Yeah, they updated the manifests for v10. I stumbled across this while I was looking at updating mine.

https://foundryvtt.com/article/manifest-migration-guide/

**Comment by Haxxer** [comment]
Fixed in 1.4.9
