### ISSUE TITLE
[BUG] Hit dice recovery fraction doesn't behave differently than default behavior

### ISSUE THREAD

**Issue by unnamed-gw** [fantasycalendar/FoundryVTT-RestRecovery#135]
**Describe the bug**
The "Hit dice recovery fraction" option doesn't change the default behavior of recovering half the missing hit dice even when the option is changed to "full", "quarter" or a "custom formula"

**To Reproduce**
1. Promt rest for the selected players.
2. Selected players chosse to end long rest.
3. Half of the hit dice are recovered independently of the chosen option.

**Expected behavior**

**Screenshots**

**Setup:**
 - Foundry Version: 10.291
 - System Version: DnD5e 2.1.4
 - Rest Recovery Version: 1.4.8
 - Browser & version: foundry app

**Active modules:**
 - Rest Recovery
 - libwrapper

**Additional context**
I tested in a world with Rest Recovery and libwrapper only, just to be sure no other module was interfering.

**Comment by Haxxer** [comment]
Fixed in 1.4.9
