### ISSUE TITLE
[BUG] Long rest hit dice recovery formula issue

### ISSUE THREAD

**Issue by Notabotnev** [fantasycalendar/FoundryVTT-RestRecovery#137]
**Describe the bug**
Despite being the only module loaded, for some strange reason the Hit dice recovery fraction formula does not seem to effect how many hit dice are recovered. 

**To Reproduce**
1. Set the hit dice recovery fraction to full. 
2. Open any character sheet that can long rest.
3. Click the long rest button, and confirm.
After doing this the character will recover half (always rounded down) of their hit dice. 

**Expected behavior**
Character hit dice should follow the Hit dice recovery fraction formula, not the 5e built in formula.

**Screenshots**
![Screenshot_62](https://user-images.githubusercontent.com/81548169/221437270-0b0516ff-011c-461d-a630-f2e71b33e507.png)
![Screenshot_63](https://user-images.githubusercontent.com/81548169/221437274-bd7fc389-395e-4b16-8b7c-a2165b423827.png)

**Setup:**
 - Foundry Version: [10.291]
 - System Version: [DND5e 2.1.5]
 - Rest Recovery Version: [1.4.9]
 - Browser & version [N/A, happens in base program as well]

**Active modules:**
 - Rest Recovery
 - libwrapper

**Additional context**
I'm sorry if this isn't enough information for the problem. It is my first time reporting a bug like this. I hope it at least helps you iron out the issue.

**Comment by Haxxer** [comment]
The latest release is 1.4.9, could you update?

**Comment by Haxxer** [comment]
Ah you edited it.

**Comment by Notabotnev** [comment]
Yeah sorry, I accidentally left all the e.g. in there, I am on the latest version, my apologies. Like I said, I'm new to this.
