### ISSUE TITLE
[BUG] Activating One D&D Exhaustion and Convenient Effects integration breaks Foundry UI

### ISSUE THREAD

**Issue by hoyer1066** [fantasycalendar/FoundryVTT-RestRecovery#140]
**Describe the bug**
- I activated exhaustion automation, Module integration for Convenient Effects, and One D&D Exhaustion, and when it reloaded the Foundry UI had broken — bottom of the ui was halfway up the screen (macro bar etc) and individual Module Settings dialogue box was locked to below the visible screen with the save button not accessible.
- Reverted to a clean foundry with only Rest Recovery module activated and the bug remained.
- Clearing recent cookies temporarily fixed the bug, but as soon as any module settings were altered or other modules activated it reverted.
- I tested with and without the Convenient Effects module active and the bug occurs in both cases.
- The bug only occurs when both One D&D Exhaustion and Convenient Effects integration are active — having either one active alone does not cause the bug.

**To Reproduce**
1. Go to 'Configure Module Settings'
2. Click on 'Configure Rest'
3. Go to 'Long Rest'
4. Tick on 'Enable exhaustion automation'
5. Set 'Exhaustion Module Integration' to 'DFreds Convenient Effects'
6. Tick on 'Enable One D&D Exhaustion'
7. Refresh
8. See error

**Expected behavior**
Not to mess the Foundry UI.

**Screenshots**
Screenshots show UI with only Rest Recovery active

View of full screen
![Capture](https://user-images.githubusercontent.com/77966438/226943280-9cf34a5b-7589-4dad-8763-4186fdd03783.JPG)

View of Configure Rest dialogue scrolled all the way down and as high on the screen as it will go
![Capture 2](https://user-images.githubusercontent.com/77966438/226943430-86eacef2-5076-4c0a-89b1-12eae779ca91.JPG)

**Setup:**
 - Foundry Version: v10.291
 - System Version: DnD5e v2.1.5
 - Rest Recovery Version: v1.4.10
 - Browser & version: Opera v96.0.4693.50

**Active modules:**
 - Rest Recovery
 - libwrapper
 - [DFreds Convenient Effects v4.1.1]
 - [socketlib]

**Additional context**
UI was not broken when checked on Firefox and Microsoft Edge with only Rest Recovery activated. Didn't test further.

**Comment by hoyer1066** [comment]
No errors in the console

**Comment by Haxxer** [comment]
@hoyer1066 I recommend you turn off DFreds' integration. OneD&D Exhaustion works without it, and simply utilizes an active effect on the actors with exhaustion of 1 or above.

**Comment by Haxxer** [comment]
Fixed in 1.4.11
