### ISSUE TITLE
[Request] Character not recover exhaustion in long rest (homebrew)

### ISSUE THREAD

**Issue by marceloabner** [fantasycalendar/FoundryVTT-RestRecovery#145]
**Is your feature request related to a problem? Please describe.**
One of the ideas from homebrew rest is not recovering from exhaustion when you get some status. This could be something you could set with an effect, or be a homebrew game rule.

**Describe the solution you'd like**
Adding an actor trait we could set ON/OFF if that character recovers from exhaustion after a long rest.

**Describe alternatives you've considered**
I think the only way is to make a macro where you give +1 when the long rest automation is run. I've tried to do the same with Effect Macro module too.

**Comment by Haxxer** [comment]
Added support for this as an active effect in 1.4.16

![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/12858387/cc9cd975-d0da-4889-a3c4-b2da3960b731)

I also added `game.restrecovery.daeFlags`, which you can use to see what is available to set with active effects:

![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/12858387/232793ac-b0ca-4868-97a4-ea145f255acc)
