### ISSUE TITLE
[Request] Hit dice recovery extension And Healers Kit 

### ISSUE THREAD

**Issue by DennisNick2026** [fantasycalendar/FoundryVTT-RestRecovery#147]
Hi, I would love to see the option of recovering hit dice on short rests, exactly like the option on Long rests.
For example, you could recover all hit dice on a long rest and half on a short rest.

If at all possible, I would love to see the integration of the Healer's Kit Dependency variant rule in the DMG page 266
"A character can't spend any Hit Dice after finishing a short rest until someone expends one use of a healer's kit to bandage and treat the character's wounds." 
I imagine this could also be used with the longest as well.
This could also be built on with the healer's feat which lets you heal a creature using a healer's kit, making it so that anytime anyone uses hit dice, they would get some extra healing from the feat if anyone has it. Assuming the character with the feat is the one to patch everyone up on a rest.

**Comment by Haxxer** [comment]
For two feature requests, it'd be better with two separate tickets. Another Healer's Kit request is already here:

https://github.com/fantasycalendar/FoundryVTT-RestRecovery/issues/102

**Comment by DennisNick2026** [comment]
Thanks for letting me know!
I have done that now.
