### ISSUE TITLE
[BUG] Drag-and-Drop Food/Water Not Working

### ISSUE THREAD

**Issue by Monsamoai** [fantasycalendar/FoundryVTT-RestRecovery#149]
**Describe the bug**
Dragging and dropping consumables into the food & water section of the rest menu does not function, only selecting options from the drop-down menu works currently.

**To Reproduce**
1. Enable Rest Recovery 5e.
2. Enable food & water in module settings.
3. Create a consumable item that is recognized as food by the module.
4. Take long rest, attempt to drag the consumable into the food & water portion of the rest menu.
5. See error

**Expected behavior**
The item dropped into the food & water section of the rest menu is added accordingly.

**Setup:**
 - Foundry Version: 10.291
 - System Version: DND5e 2.2.2
 - Rest Recovery Version: 1.4.12

**Active modules:**
 - Rest Recovery for 5e
 - libwrapper (1.12.12.1)
 - Midi QOL (10.0.57)
 - DAE (10.0.37)
 - socketlib (1.0.13)
 - Tidy5e Sheet (0.9.7)

**Comment by Haxxer** [comment]
Fixed in 1.4.13
