### ISSUE TITLE
[Request] Select Food/Water Item Quantity

### ISSUE THREAD

**Issue by Monsamoai** [fantasycalendar/FoundryVTT-RestRecovery#150]
**Is your feature request related to a problem? Please describe.**
This feature request comes from my use of gritty realism rest rules (long rest: 7 days, short rest: 1 day), where taking a long rest requires multiple meals and drinks to satiate the food/water requirements. Currently, when using this module, you can only use one of a particular food or drink, unable to choose multiple of that same item within the stack.

To create an example scenario, say a player wants to consume 7 rations from their inventory to complete the long rest. The player selects their rations from the food & water rest menu, but they can only select one from the stack. If they go back into the drop-down menu to try and select another ration, it's not an option. For situations where more than one of the same food/drink item need to be consumed from a stack, it is not possible to do so with the module's current formatting.

**Describe the solution you'd like**
Alongside the number of charges consumed from a particular consumable, another option should be available to specify the number of items consumed from that stack.

**Describe alternatives you've considered**
Another way is to use the drag-and-drop/drop-down menu to place the same item again, and the module recognizes that it will be consuming 2 from that item's stack.

**Comment by Haxxer** [comment]
This is a bug, and it was fixed in 1.4.13
