### ISSUE TITLE
[Request] Variant Healing - Healer's Kit Dependency

### ISSUE THREAD

**Issue by L0KI7777** [fantasycalendar/FoundryVTT-RestRecovery#152]
**Is your feature request related to a problem? Please describe.**
The Dungeon Master's Guide suggests a variant rule for healing which requires a use of a healer's kit to roll hit dice. This would complement well the Slow Natural Healing rule and follows the same automation as consuming food and water.

**Describe the solution you'd like**
It would be interesting to implement the use of a healer's kit's charges when hit dice are rolled, similar to how food and water must be selected.

Healer's Kit Dependency
A character can't spend any Hit Dice after finishing a short rest or long rest until someone expends one use of a healer's kit to bandage and treat the character's wounds.

**Comment by Haxxer** [comment]
If you scroll down, this feature has already been requested.
