### ISSUE TITLE
[BUG] Song of Rest issue

### ISSUE THREAD

**Issue by MythicalRollers** [fantasycalendar/FoundryVTT-RestRecovery#154]
**Describe the bug**
When using short rest, and rolling hit dice, with a bard with the Song of Rest, the "Song" rolls 11d8 per character instead of 1d8.

**To Reproduce**
1. Go to 'any character sheet'
2. Click on 'Short Rest'
3. Click on 'Roll'

**Expected behavior**
Song of rest to only roll 1d8 once per character resting.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/106455111/046c9f89-edd6-495a-bb4a-a2227d4cbc8a)

**Setup:**
 - Rest Recovery for 5e 1.4.12
 - Foundry V11
 - dnd5e 2.3.0
 - Google Chrome 115.0.5790.173

**Active modules:**

About Time v;
Action Pack v;
Active-Auras v;
Active Token Effects v;
Advantage Reminder for dnd5e v;
Arbron’s Summoning v;
Archon (Masked Items) v;
Automated Animations v;
A/V Quality of Life v;
Build-a-Bonus v;
Chat Commander v;
Chris's Premades v;
CodeMirror v;
Condition Lab & Triggler v;
Custom CSS v;
Cyrens Maps for Icewind Dale v;
D&D5e Animations v;
DDB-Importer: A D&D Beyond Integrator v;
DFreds Convenient Effects v;
Dice So Nice! v;
Dice So Nice - Weighted Companion Cube Dice Set v;
Dice Tray v;
DnD5e Ui v;
Drag Ruler v;
Dynamic effects using Active Effects v;
Effect Macro v;
Entice with Dice so Nice v;
Find the culprit v;
Flying Tokens v;
Force Client Controls v;
Force Client Settings v;
Foundry Community Macros v;
Foundry Community Tables v;
FXMaster v;
Hero Creation Tool for DnD5E v;
Hover Distance v;
Illandril's Inventory Sorter (5e) v;
Illandril's Pact Slot Third Caster (5e) v;
Item Containers v;
Item Macro v;
Item Piles v;
Items with Spells DnD5e v;
Jack Kerouac's Animated Spell Effects: Cartoon v;
JB2A - Jules and Ben's Animated Assets - Free Content v;
JB2A - Patreon Complete Collection v;
Jinker's Animated Art Pack v;
Library: Scene Packer v;
libWrapper v;
Link Item and Resource DnD5e v;
LiveKit AVClient v;
Lordu's Custom Dice for Dice So Nice v;
Midi QOL v;
Midi SRD v;
Monk's Active Tile Triggers v;
Monk's Bloodsplats v;
Monk's Chat Timer v;
Monk's Combat Details v;
Monk's Combat Marker v;
Monk's Little Details v;
Monk's Scene Navigation v;
Monk's Sound Enhancements v;
Monk's TokenBar v;
Monk's Wall Enhancement v;
Mythical Rollers Compendium v;
Pointers v;
PopOut! v;
Quick Insert - Search Widget v;
Rest Recovery for 5E v;
Sequencer v;
Sidebar and Windows Resizer v;
Sidebar Macros v;
Simple Calendar v;
SmallTime v;
Small Visual Tweaks v;
Smart Target v;
socketlib v;
SoundFx Library v;
Squadron v;
Stream View v;
Sweet Nothings v;
Tagger v;
Template Macro v;
Tidy5e Sheet v;
Tidy UI - Game Settings v;
Times Up v;
Token Attacher v;
Token Magic FX v;
Token Variant Art v;
User Latency v;
Vision 5e v;
Visual Active Effects v;
Wall Height v;
Warp Gate v;
Wild Magic Surge 5e v;
World Scripter v;

**Additional context**
NA

**Comment by Haxxer** [comment]
Double check the song of rest feature formula, and the bard class formula. They may have an additional 1 in them, as it uses the feature's formula to roll.

**Comment by MythicalRollers** [comment]
Helps if the feature is setup to use the class formula... My bad.  Thank you.
