### ISSUE TITLE
[BUG] RestRecovery Bugs

### ISSUE THREAD

**Issue by tubaboss9** [fantasycalendar/FoundryVTT-RestRecovery#155]
Hello, I just downloaded this module and started using it for HP/HD automation and customization. It is working smoothly but there are two bugs I have noticed.

**BUG 1 - PERIAPT OF WOUND CLOSURE**
When a character rests using this item, the hit die value is doubled but the constitution modifier is not. What is happening is (HD Value)*2 + constitution modifier instead of (HD Value + constitution modifier)*2. See Screenshot 1 for example.
![Screenshot 1 - Rest Recovery](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/144073639/d46706b3-c429-42d2-a17d-001f51245cef)

**BUG 2 - HIT DIE RECOVERY BEFORE REST**
I changed the settings to turn off hit point recovery, change hit die recovery to half (rounded down), and enabled hit dice recovery before finishing long rest. What happens is when I start the long rest I recover half of my hit dice (as I am supposed to) then when I finish the long rest it recovers half the hit dice again. Screenshot 2 shows the character before clicking long rest, screenshot 3 shows the character after beginning the long rest, and screenshot 4 shows the character after finishing the long rest. 
![Screenshot 2 - Rest Recovery](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/144073639/0de53afe-3840-4523-98b8-fd02495ef62a)
![Screenshot 3 - Rest Recovery](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/144073639/1682f850-e47d-4cfd-a007-63870c54cbdc)
![Screenshot 4 - Rest Recovery](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/144073639/08ad76bd-c280-4878-9461-04c4b0a56e98)

**Comment by Haxxer** [comment]
Fixed both bugs in 1.4.14, please create separate tickets for each bug in the future.

Added the first one as an option, as the the Periapt says "double the number of hit points it _(the roll)_ restores", which leaves it a bit up to your own interpretation.

![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/12858387/68580334-ab7d-43d5-b266-24e9106a6fea)

**Comment by tubaboss9** [comment]
Fair enough on the interpretation. I just checked the "Multiply Total Result" option, and it's doubling the modifier, not the total result. Instead of (Hit Die + Modifier)*2, it is calculating it as Hit Die + Modifier*2.
I'll leave another ticket for your tracking purposes.
Thanks,Nathan    On Sunday, September 24, 2023 at 01:58:21 PM EDT, Adam Oresten ***@***.***> wrote:  
 
 


Fixed both bugs in 1.4.14, please create separate tickets for each bug in the future.

Added the first one as an option, as the the Periapt says "double the number of hit points it (the roll) restores", which leaves it a bit up to your own interpretation.

**Comment by tubaboss9** [comment]
Fair enough on the interpretation. I just checked the "Multiply Total Result" option, and it's doubling the modifier, not the total result. Instead of (Hit Die + Modifier)*2, it is calculating it as Hit Die + Modifier*2.

I'll leave another ticket for your tracking purposes.

Thanks,
Nathan
