### ISSUE TITLE
[BUG] DOUBLE CONSUMPTION OF RATIONS

### ISSUE THREAD

**Issue by l3lackk9** [fantasycalendar/FoundryVTT-RestRecovery#156]
When rations are set to 1/1 but have a stack of more than 1 copy, the rations will be consumed twice over a rest.  This doesn't matter what type it is, food or water, it always consumes two stacks of the item.  It doesn't happen when charges are set to more than 1/1, however, once it reaches 1/2 and the item is consumed, the double-consumption bug returns.

**To Reproduce**
1. Add food or water item as a consumable item, set charges to 1/1, add multiple stacks of that item.
2. Click on rest, set the item to be consumed over a rest.
3. Confirm the consumption.
4. Two stacks of the item will be consumed.

**Expected behavior**
I'm expecting either the charges to be set to 0 if the item is not flagged as "remove on empty" and only one item in the stack to be removed any time the item is consumed.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/116856005/8b3f6285-6b1a-455d-8658-ad5b36ed6b10)
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/116856005/789431b7-c444-4515-81b6-3eafde8977f8)
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/116856005/9ce7305f-fea1-4b12-b0e3-411ce85833a1)
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/116856005/aaf9b7bc-832a-48de-883b-66f0adf0abb7)
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/116856005/61fd9200-b853-4f73-b3a9-827f60ba1261)

When the charges are set to 1/1 each, it still happens.
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/116856005/6121da13-f6ae-4594-a046-64c802d7b3c5)
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/116856005/87a2e702-5a35-4723-95ea-4b5c46d1e267)
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/116856005/2722217a-ac6b-4aa7-a213-575566add49e)

**Setup:**
 - Foundry Version: v11 build 308
 - System Version: DnD5e 2.3.1
 - Rest Recovery Version: 1.4.13
 - No browser used, this is straight out of the foundry program.

**Active modules:**
 - Rest Recovery
 - libwrapper

**Comment by Haxxer** [comment]
Fixed in 1.4.14
