### ISSUE TITLE
[BUG] OneDnD Exhaustion not working

### ISSUE THREAD

**Issue by TinTanTiddlyTRex** [fantasycalendar/FoundryVTT-RestRecovery#157]
I tested the rest recovery module because I wanted to integrate the onednd exhaustion rules. I checked the boxes and it shows the exhaustion until level 10, but it does not calculate the -1 per exhaustion in rolls.
Could you help me out? 

**To Reproduce**
1. Go to Character sheet
2. Click on Exhaustion
3. click on 1-10 
4. see it not substract the -*exhaustion level* from the roll

**Expected behavior**
It should set the exhaustion to a level of 1-10 and distract the given level from all ability throws.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/144317808/fea877e9-fe6d-40bb-86ae-792873f82366)
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/144317808/fd65071f-cc5d-4521-9007-0747ea060cf3)
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/144317808/f8a579b7-9801-464c-b74f-69b8df67b0a3)

**Setup:**
 - Foundry Version: 11.308
 - System Version: 2.3.1
 - Rest Recovery Version: 1.4.13
 

**Active modules:**
 - Rest Recovery
 - libwrapper
 

**Additional context**

When I look at the note, this could be intended, but is the only thing this setting does to extend the exhaustion bar to 10?

I also noticed, that when I do the food and water automation, it reduces the rations by 2 per long rest instead of 1 even when giving the ration 1 charge and activating the "1 charge is for a whole day" setting.

**Comment by Haxxer** [comment]
Fixed in 1.4.14
