### ISSUE TITLE
Song of Rest - Only when present in scene

### ISSUE THREAD

**Issue by tubaboss9** [fantasycalendar/FoundryVTT-RestRecovery#160]
Hello,
Thank you for the hard work on this module. It really helps streamline resting and homebrew resting mechanics in my game. 

One quirk that I do have to work around when using this module is Song of Rest. Whenever the group short rests, Song of Rest always applies, even if the Bard is not present in the scene. For my campaign, this entails a minority of cases, but this means any one-shot I run in the same world will also have Song of Rest applied from a Bard who is neither in the scene nor in the one-shot.

Is there a way around this or an easy way this could be addressed besides deleting Song of Rest and re-adding it when the bard rejoins the scene?

**Comment by Haxxer** [comment]
Added support for this in 1.4.16:

`- Tweaked rests that are prompted by GMs to now only consider the prompted characters when determining active features such as Song of Rest and the Chef feat`
