### ISSUE TITLE
[BUG] ENTER BUG NAME HERE

### ISSUE THREAD

**Issue by YBSker** [fantasycalendar/FoundryVTT-RestRecovery#161]
**Describe the bug**
Setting units of water required per day to a non-1 number and long resting while selecting a consumable marked as water to be recognized by Rest-Recovery plugin results in only 1 of the consumable being consumed.

**To Reproduce**
1. Go to Rest Recovery Configuration
2. Enable Food/Water Automation and set Units of water required per day to non-0/1 number
3. Create and set a consumable to be recognized by Rest Recovery plugin as Water with more than or equal quantity to water requirement per day set in step 2 in a character sheet
5. Long Rest character and add water consumable to be consumed with x units set in step 2
6. Appropriate amount will be claimed to have been used. Check character sheet. Only 1 of consumable resource will be subtracted from starting total.

**Expected behavior**
Amount set to be consumed in long rest prompt should be subtracted from original total of consumable quantity in character sheet.

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/46542771/2a9a9dec-1591-4e2f-ad3e-b74120964ca9)
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/46542771/4f3a6989-8ecb-474b-98a7-629a9f84dd90)
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/46542771/3212c8b2-cc79-4614-a496-4981a210d25b)

**Setup:**
 - Foundry Version: [11.309
 - System Version: DND5e 2.3.1
 - Rest Recovery Version: 1.4.14
 - Browser & version Firefox 117.0.1

**Active modules:**
 - Rest Recovery
 - libwrapper

**Comment by Haxxer** [comment]
Fixed yet again in 1.4.15

(don't forget the ticket title! :D)
