### ISSUE TITLE
[BUG] Unable to export profile

### ISSUE THREAD

**Issue by DiceAndEasy** [fantasycalendar/FoundryVTT-RestRecovery#162]
**Describe the bug**
When you click the Export Profile button in the rest recovery configuration, nothing happens. The following error message gets printed in the console:
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/86520580/b8ff5169-7765-4004-a4ce-fb36ee9ea741)

**To Reproduce**
1. Launch Foundry
2. Launch a world
3. Activate Rest Recovery
4. Go to Game Settings
5. Go to Configure Settings
6. Find Rest Recovery and click Configure Rest
7. Click Export Profile at the top of the new window and notice nothing happens

**Expected behavior**
Clicking the Export Profile button should give you a file that can be used to import your profile to another Foundry world.

**Setup:**
 - Foundry Version: 11.313
 - System Version: DnD 5e 2.3.1
 - Rest Recovery Version: 1.4.17
 - Browser & version Google Chrome

**Active modules:**
 - Rest Recovery
 - libwrapper

**Comment by Haxxer** [comment]
Fixed in 1.5.0
