### ISSUE TITLE
[Request] New Day button

### ISSUE THREAD

**Issue by BenNelsonNeb** [fantasycalendar/FoundryVTT-RestRecovery#165]
Why is the New Day button on the GM "prompt for rest" instead in not in the "Long Rest" profile section?  I guess I understand that a Long Rest could happen at any point in the day, but it would be very rare for a long rest not to go into the next day. It is easy to forget to check that box when it should be the default for a long rest. Unless I am missing something, not sure why that option is not the norm for every long rest.

Wondering if there can be a main option to make "New Day" checked by default or a profile option to override if that is checked or not. I would think it should be checked all the time, and rarely unchecked.  

(personal option) I also think the New Day button doesn't need to be on the GM "prompt for rest" since it could be part of the profile, a separate profile could be created for those super rare long rest performed during the day. But that might just be a cosmetic thing to me.

**Comment by Haxxer** [comment]
If you rest at 10am, is it a new day? This is as designed.

**Comment by BenNelsonNeb** [comment]
Maybe I misunderstood the option.  I thought it would only trigger on a long rest, but from your comment it sounds like it can happen anytime. That is why I suggested tying it to a long rest option. Can a short rest happen at 10, of course, but I would not trigger a new day. Will 99% of long rests result in a new day, yes. I guess it is possible to have a new day happen on a short rest? seems really rare. Only a suggestion, as it seemed oddly placed, but if it is part of the design I understand.

**Comment by Haxxer** [comment]
A short rest can happen at midnight, and a long rest can end before midnight. Therefore, it is best to leave the checkbox in case that does happen, as I would rather it be an option for everyone to consider. If you wish this to be changed, this module is open source and you are able to submit pull requests to make these changes, but I will not implement them :)

**Comment by BenNelsonNeb** [comment]
Cool. Again, just a suggestion. Love the module.
