### ISSUE TITLE
[Request] Dynamic Active Effect flag to disable exhaustion recovery

### ISSUE THREAD

**Issue by maxobremer** [fantasycalendar/FoundryVTT-RestRecovery#169]
**Is your feature request related to a problem? Please describe.**
It would be nice if there was a flag for an active effect that would disable the automatic exhaustion recovery. This way if a player has a disease or curse that prevents natural exhaustion recovery, it can easily be disabled on such a character.

**Describe the solution you'd like**
A active effect flag that that stops exhaustion recovery like rest-recovery.prevent.exhaustionRecovery 1

**Describe alternatives you've considered**
A effect macro that triggers on a long rest to add a point of exhaustion to counteract the one loosed during a long rest..

**Additional context**
Nice work on the module so far.

**Comment by Haxxer** [comment]
Check `game.restrecovery.daeFlags`, this is already supported with `flags.dae.rest-recovery.prevent.exhaustionRecovery`

**Comment by maxobremer** [comment]
a my bad, i did not see it in the wiki so i assumed it wasn't a thing. Can it maybe be added there?
