### ISSUE TITLE
[BUG] Spell slots and items aren't consumed anymore

### ISSUE THREAD

**Issue by FalconPilot** [fantasycalendar/FoundryVTT-RestRecovery#170]
**Describe the bug**
When the module is active, spell slots aren't consumed anymore on spellcasts and items that are supposed to be destroyed on 0 charges don't get destroyed. It only started happening after the very last update. There aren't any errors in the console, so I have no further info on this :/

**To Reproduce**
1. Create a DnD5e table
2. Install/activate the module
3. Try to drink a potion of healing or to use a spell

**Expected behavior**
It should consume the slot/item properly

**Setup:**
 - Foundry Version: 11.315 [Stable]
 - System Version: DnD5e 2.4.0
 - Rest Recovery Version: 1.4.17
 - Browser & version Brave 1.60.110 Chromium

**Active modules:**
 - Rest Recovery
 - libwrapper
 - Chat Portrait
 - Monk's Combat Market
 - The Forge

**Additional context**
I isolated this module being the sole responsible for this - I tried disabling every single module but this one and libwrapper, and the bug appeared. If I keep a vanilla table without libwrapper and this module, the bug fixes itself. Perhaps something just broke due to the latest update for some reason?

**Comment by BladeFireLight** [comment]
This also effects using arrows with a bow. with only this mod loaded assigning arrows as ammunition on a short bow.  on clicking attack in chat, the roll type dialog never shows.

**Comment by tposney** [comment]
The specific problems is that the signature to _handleConsumeResource has changed in dnd 2,4, it expects a config as the first parameter.

However the whole _getUsageUpdates code has changed in 2.4 so the patch_getUsageUpdates will have to be redone to match the new dnd2.4 way of doing things.

**Comment by Haxxer** [comment]
Fixed in 2.4.0
