### ISSUE TITLE
[BUG] Dont see Food/Water option on items Details. 

### ISSUE THREAD

**Issue by BenNelsonNeb** [fantasycalendar/FoundryVTT-RestRecovery#171]
**Describe the bug**
Since updating D&D 5e to the latest version, I cannot see the Food/Water option on an item under the details section. Items currently setup appear to be working but not able to adjust or create new food/water options.  

**To Reproduce**
Create new item > Consumable type > under Details > missing food/water options. 
or
View current items previously created as food/water > view details > missing food/water options.

**Expected behavior**
Option to make food/water. 

**Setup:**
 - Foundry Version: 11.315
 - System Version: DND5e 2.4.0
 - Rest Recovery Version: 1.4.7

**Active modules:**
 - Rest Recovery
 - libwrapper

**Additional context**
Did try without any other modules except RR and libwrapper.  Same issues.  It does appear that 5e update made change.

**Comment by Haxxer** [comment]
Do you have food & water automation enabled?

**Comment by Haxxer** [comment]
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/12858387/27f48134-1635-499f-8e17-aea4b89a2de2)
