### ISSUE TITLE
[Request] Support for Food and Water requirements for creatures of different sizes

### ISSUE THREAD

**Issue by DeadDuck64** [fantasycalendar/FoundryVTT-RestRecovery#175]
**Is your feature request related to a problem? Please describe.**
Small characters need 1/4 pound, Large needs 4 pounds, Huge 16 pounds and so on...

**Describe the solution you'd like**
There needs to be a option to auto calculate the amount needed for each size besides just the universal food/water needed amount.

**Describe alternatives you've considered**
The module should be able to read the creature size automatically and there also should be a numeric input in the module options for custom food/water needs per size.

**Additional context**
It would be nice to include any way to make the NPCs be able to take food from another character sheet owned by the same user, for players to be able to feed their animals.

**Comment by Haxxer** [comment]
Each character can be configured to have different food & water requirements in their traits configuration. I think that covers your request, does it not?

**Comment by DanielTheBard** [comment]
I came looking to suggest this & found it closed. Automating the process so it's one less thing I need to manually edit for player characters would be helpful & appreciated. I was thinking less of a default calculation & more of an optional setting to either set a different number or a number to multiply by for each size category (& even then, I was only thinking of Small/Medium, but could see Tiny & Large too). Your solution makes sense & I will do that for my current small characters. Hopefully, I'll remember to do it for future players 😬
