### ISSUE TITLE
[Request] Allow food and water automation on short rests

### ISSUE THREAD

**Issue by nolorfin** [fantasycalendar/FoundryVTT-RestRecovery#176]
**Is your feature request related to a problem? Please describe.**
The DMG has an optional rule to set short rests to 8 hours and long rests to one week. This is the option we use at my table. This means one full day of activity/travel ends on a short rest, not a long one.

**Describe the solution you'd like**
Allow food/water automation to work on short rests. Other features related to long rests, when understood as sleep time, would also be nice, like armor effects on sleeping.

**Describe alternatives you've considered**
My alternative solution is to set our short rests as "fake long rests" that don't restore resources like spells slots, etc. But I've found this creates conflicts with other game mechanics and automations.

**Comment by Haxxer** [comment]
You can do this with the rest variant setting at the top of dnd5e's system settings.

**Comment by Haxxer** [comment]
Did you also try the quick setup button in the rest recovery settings? These things can be found out by looking around a bit ;)

**Comment by nolorfin** [comment]
It may not look like it, but I had actually studied the settings thoroughly before posting this issue. I think my problem was my interpretation of this section:
<img width="589" alt="Screenshot 2023-12-24 at 13 10 06" src="https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/72673748/f7bcdff8-d33d-4870-baff-c207dfa3136f">
I understood it meant that food and water automation would only work during long rests. I see now that I can tell the mod that a short rest happens on a new day, and food and water automation will kick in.
My problem stands, though, because using the settings you recommend, a short rest without eating and drinking still doesn't cause one level of exhaustion, because the mod understands I would need to spend seven days (the timeframe for a long rest) without food or water before one level of exhaustion is accrued.
<img width="391" alt="Screenshot 2023-12-24 at 13 15 02" src="https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/72673748/747eff13-ede8-4fbf-a5d2-c77f90ee11ab">
Am I missing something else? Thank you.

**Comment by nolorfin** [comment]
I found the problem. The SRD's Waterskin items is not set to be "destroyed on empty", which means after using it once, it runs out of charges, and when your mod checks if there's water in the PC's inventory, it finds an empty waterskin and ignores it, even though there may be 20 other full waterskins in the inventory.

**Comment by Haxxer** [comment]
Please create a ticket for that bug - makes it easier to track.

**Comment by nolorfin** [comment]
Done.
