### ISSUE TITLE
[BUG] SHORT REST HIT DICE RECOVERY

### ISSUE THREAD

**Issue by DudeAndre** [fantasycalendar/FoundryVTT-RestRecovery#178]
As soon as I click the "Finish Short Rest" button I get half my total hit dice back, as if it was a Long Rest and not just a Short One.

**Setup:**
 - Foundry Version: 11.315
 - System Version: DND5e 2.4.1
 - Rest Recovery Version: 1.5.2

**Comment by Haxxer** [comment]
Fixed in 1.5.3
