### ISSUE TITLE
[BUG] Arcane Recovery Does Not Recover Spell Slots

### ISSUE THREAD

**Issue by DiceAndEasy** [fantasycalendar/FoundryVTT-RestRecovery#179]
**Describe the bug**
When taking a short rest with a wizard PC and selecting spell slots to recover with Arcane Recovery, the spell slots won't be recovered and a use of Arcane Recovery will not be expended once the short rest has been finished. The following error message is logged into the console once the short rest ends:
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/86520580/631f2a46-fff4-41a2-b24a-c54e0f92e140)

**To Reproduce**
1. Create a Wizard player character of at least 1st level
2. Open their character sheet
3. Remove some spell slots from them
4. Click the short rest button on the character sheet
5. Click on the "Magic Recovery" tab
6. Select the spell slot(s) to recover
7. Click "Finish Short Rest"
8. Notice that no spell slots have been regained

**Expected behavior**
The number of spell slots selected during the short rest UI flow should be added to the Wizard's character sheet and a use of Arcane Recovery should be expended.

**Screenshots**
Video of the issue:

https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/86520580/d3815599-4052-4c1c-9d2d-ed131bd50d0f

**Setup:**
 - Foundry Version: 11.315
 - System Version: DnD 5e 2.4.1
 - Rest Recovery Version: 1.5.3
 - Browser & version Google Chrome 120.0.6099.130 (Official Build) (64-bit)
 
**Active modules:**
 - Rest Recovery
 - libwrapper
 - Dice so Nice!

**Additional context**
Running Foundry through The Forge.

**Comment by Haxxer** [comment]
Fixed in 1.5.4

**Comment by DiceAndEasy** [comment]
Issue verified as fixed. Thanks for the update!
