### ISSUE TITLE
Missing localization

### ISSUE THREAD

**Issue by DarKDinDoN** [fantasycalendar/FoundryVTT-RestRecovery#18]
Hello,

Here are some messages that are not localized:

![image](https://user-images.githubusercontent.com/1687854/158221621-2b4e7fec-962d-41cf-b08d-cda911aaec58.png)

![image](https://user-images.githubusercontent.com/1687854/158221629-970d0c9c-ba19-4f95-b9d7-3c39cab7498b.png)

![image](https://user-images.githubusercontent.com/1687854/158221752-8dfcd122-fdf0-4241-8c9e-abde97924453.png)
(levelText)

**Comment by Haxxer** [comment]
Thank you, I will provide localization for this!

**Comment by DarKDinDoN** [comment]
> Reference in new issu

Great, I'll provide the French translation once this is released 😸

**Comment by Haxxer** [comment]
Added localization in 1.0.2, thank you for your support!
