### ISSUE TITLE
[BUG] Song of Rest d6 healing not applied during short rest

### ISSUE THREAD

**Issue by DiceAndEasy** [fantasycalendar/FoundryVTT-RestRecovery#180]
**Describe the bug**
If you take a short rest with a Bard of level 2 or higher and you use hit dice to recover HP, at the end of the short rest, you will notice that the d6 healing from Song of Rest is not rolled or applied. The following error message is logged into the console once the short rest ends:

![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/86520580/aff04e66-7aa1-4bd6-b4ba-09ef1575df51)

**To Reproduce**
1. Create a Bard player character of at least 2nd level
2. Open their character sheet
3. Remove some HP from them
4. Click the short rest button on the character sheet
5. Select the amount of Hit Dice you want to use and click "Roll"
6. Click "Finish Short Rest"
7. Notice that the extra d6 for healing was not rolled or applied

**Expected behavior**
After clicking "Finish Short Rest" the d6 should automatically be rolled for all affected players and be added to their HP recovery.

**Screenshots**
Video of the issue:

https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/86520580/3238b769-fad8-4ce2-a8e4-92437ca09f2f

**Setup:**
- Foundry Version: 11.315
- System Version: DnD 5e 2.4.1
- Rest Recovery Version: 1.5.3
- Browser & version Google Chrome 120.0.6099.130 (Official Build) (64-bit)

**Active modules:**
 - Rest Recovery
 - libwrapper
 - Dice so Nice!

**Additional context**
Running Foundry through The Forge.

**Comment by Haxxer** [comment]
This should be fixed in 1.5.3 - if it does not fix it, double check that the bard character is assigned to a player and that you have the "ignore inactive players" setting enabled.

**Comment by DiceAndEasy** [comment]
The issue is fixed and Song of Rest dice auto rolling works if the "ignore inactive players" is disabled. With it enabled, the roll did not happen.

Also the GM was not able to trigger the Song of Rest roll, only the owning player can.
