### ISSUE TITLE
[BUG] ReferenceError interrupts rest-workflow and prevents food & water workflow from working

### ISSUE THREAD

**Issue by JaysonMendoza** [fantasycalendar/FoundryVTT-RestRecovery#181]
This is a logical in your code. So I'll not put all the details you normally expect.

![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/43111928/8fad010b-d246-4f89-a3ae-46cd0e1e97d3)

rest-workflow.js::790 reads the value "hitDiceRecovered" which has fallen out of scope and is undefined by line 790. 

I don't fully understand the logic of your code yet so I didn't fix it and push since I'm not quite sure where you want to place that line. Though I suspect you want it on line 788.

This causes error handling and that is breaking the consumption of items and the resetting of the foood/water sated values.

When I was testing I had actors who consumed food/water before resting forever having enough food and water no matter how many long rests I did. I also had actors who tried to consume during rest always complete the rest without ever consuming any items.

I'd love to help with the module eventually given time. Though I'm unsure how to create a development environment for foundry so I can start to learn the various  API's and event systems.

**Comment by JaysonMendoza** [comment]
I made a commit and PR with my recommended change if you think that my fix idea was right. I'm looking into how to test properly so I can potentially help in other areas.

**Comment by Haxxer** [comment]
Fixed in 1.5.4, thanks for the contribution!
