### ISSUE TITLE
[BUG] No item charge recovery during long rest

### ISSUE THREAD

**Issue by pefcs** [fantasycalendar/FoundryVTT-RestRecovery#185]
When doing long rest, neither of the formulas are used for item charge recovery, and no item charges are restored.

I tried to set both, or only the top one, only the bottom one, nothing helped. Without the module activated, the charges are rolled and charged properly during long rest.

**To Reproduce**
1. An item with charges, charges < @charges.max
2. Take long rest

**Expected behavior**
Charges are recovered based on the recovery method (eg. 1d6 + 2 - then roll a d6 and add the roll value + 2 to the charges limited with charges.max)

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/118229534/99875c96-5c52-4e5a-9e65-cf632a93954f)

**Setup:**
 - Foundry Version: [v11.315]
 - System Version: [DND5e 2.4.1]
 - Rest Recovery Version: [1.5.4]
 - Browser & version [Foundry Desktop Client]

**Active modules:**
 - Rest Recovery
 - libwrapper
 - Simple calendar

**Additional context**
Turning off the Simple Calendar module, or turning off the Simple Calendar integration fixes the issue

![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/118229534/2a7c50a4-326e-4f59-84e6-d0ce68abbabe)

Simple Calendar config is set to Mixed

![image](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/118229534/2ac8c9e0-dc5f-4840-ae95-a4368695b2ff)

**Comment by Haxxer** [comment]
What is your simple calendar version?

**Comment by pefcs** [comment]
v2.4.3
