### ISSUE TITLE
Localization error for Natural Recovery

### ISSUE THREAD

**Issue by DarKDinDoN** [fantasycalendar/FoundryVTT-RestRecovery#19]
Hello,

There is an issue with the localization of Natural Recovery.

The setting defaults to "NaturalRecovery": https://github.com/fantasycalendar/FoundryVTT-RestRecovery/blob/main/scripts/constants.js#L80

But the localization key is "DruidRecovery": https://github.com/fantasycalendar/FoundryVTT-RestRecovery/blob/main/languages/en.json#L12

**Comment by Haxxer** [comment]
Fixed in 1.0.2
