### ISSUE TITLE
Bug with italian language preference (so i suppose with "Babele" module and/or "Italian Modules Translation" module) and  amount of food unit required for a long rest.

### ISSUE THREAD

**Issue by Booyeto** [fantasycalendar/FoundryVTT-RestRecovery#191]
**Describe the bug**
I've seen that if i've set italian in the general setting as languange preference,the amount of food required for a long rest  set in the setting  is 10 timer higher when an actor is taking long rest.  For example if i put 1 unit of food in th configuration setting, when the actor is taking a long rest rest the unit of food to consume appear to be 11, if i put 2 unit in the configuration setting, the amount of food in the sheet become 21. 
That happen only with the food unit and not with the water unit.  
So I suppose there is a bug with the modules "Babele" and/or "Italian Modules Translatiion".
If i put english as language preference the bug no longer exist. 

With English language 
![Screenshot 2024-03-26 172107](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/165058504/2a5d1925-2258-46ca-8611-9d3524151e36)
![Screenshot 2024-03-26 172131](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/165058504/6371acf4-f15a-4cef-88f4-5a8aca7d7248)

With Italian language 
![Screenshot 2024-03-26 171855](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/165058504/355ec689-7167-4fb4-a039-4d03dc5bb263)

![Screenshot 2024-03-26 171940](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/assets/165058504/c2bdf088-3b13-42cd-845d-6a21671e8254)

**Setup:**
-Foundry version 11
-System 5e 3.0.4

**Comment by Haxxer** [comment]
I cannot fix issues that is caused by other modules.
