### ISSUE TITLE
Suggestion: Short Rest: Roll until at X HP

### ISSUE THREAD

**Issue by BadIdeasBureau** [fantasycalendar/FoundryVTT-RestRecovery#20]
There is a mostly unused feature in the dnd5e system which allows for automatically rolling hit dice on a short rest until the number of missing HP is below a threshold, where by doing `actor.shortRest({dialog: false, autoHD: true, autoHDThreshold})` the 5e system will automatically roll hit dice until the number of missing HP is less than the threshold (or the actor runs out of hit dice).  Exposing this in the short rest dialog would be a very nice enhancement here, which seems in scope for this module.

Code in the 5e repo: https://gitlab.com/foundrynet/dnd5e/-/blob/master/module/actor/entity.js#L1277

**Comment by Haxxer** [comment]
Added in 1.0.4
