### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DarKDinDoN** [fantasycalendar/FoundryVTT-RestRecovery#23]
Hello,

Was implementing a homebrew rule for my own purpose. Noticed an error here: https://github.com/fantasycalendar/FoundryVTT-RestRecovery/blob/main/scripts/formapplications/short-rest/short-rest-shell.svelte#L5

Should be `import HealthBar from "../components/HealthBar.svelte";` ("B" uppercase)
Node throws an error on my machine.

**Comment by Haxxer** [comment]
Ah, thank you for letting me know, I'll fix that and integrate your localization :)
