### ISSUE TITLE
[Feature request] Homebrew long rest healing and short rest limit.

### ISSUE THREAD

**Issue by Fridan99** [fantasycalendar/FoundryVTT-RestRecovery#26]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
-

**Additional context**
Option 1. It would be useful to implement a homebrew rule in the Long Rest (Hit Points Recovery Fraction) option. Some people use formulas or default values. In my case I use the 3.5 d&d rule where 3 + @abilities.con.mod is recovered. (In addition to the possibility of using hit dice).

Option 2. It would be useful if there was an option to set limits to the short rest uses (none, 1, 2, 3, 4....). In my case I use a variant where there is a limit of 2 (so until a long rest is completed, you cannot use a short rest again if this limit has been reached). 

Well, these are just ideas in case they help.

**Comment by Haxxer** [comment]
These sound like two distinct requests. Could you please make a unique request for each entry?

**Comment by Fridan99** [comment]
Sure.
