### ISSUE TITLE
[Bug] Too many hit dice are regained before a long rest

### ISSUE THREAD

**Issue by ctbritt** [fantasycalendar/FoundryVTT-RestRecovery#29]
**Describe the bug**
For some reason, this module thinks all my players have 13 hit dice, even though they're only level 9.

**To Reproduce**
no real way to reproduce it. It's just always there. 

**Expected behavior**
Hit dice that match their levels

**Screenshots**
![Screen Shot 2022-03-23 at 1 05 09 PM](https://user-images.githubusercontent.com/4516034/159755832-5f2ce86f-b8e3-4736-803c-a5819201883b.png)
(A 9th level wizard)

![Screen Shot 2022-03-23 at 1 05 27 PM](https://user-images.githubusercontent.com/4516034/159755862-efa5eac9-f1d2-4f7f-9de3-63a006cc5dc6.png)
(An 8th level rogue/1st level fighter multiclass)

**Setup:**
 - Foundry Version: 9.255
 - System Version: DND5e 1.5.7
 - Rest Recovery: 1.0.5
 - Browser & version Google Chrome 99.0.4844.83 (Official Build) (arm64)

**Active modules:**
 - Rest Recovery
 - libwrapper
 - no other modules in use. 

**Additional context**
No error messages, either.

**Comment by Haxxer** [comment]
Please check your settings to make sure you don't have "regain hit dice at the start of a long rest"

**Comment by ctbritt** [comment]
Welp, that did it. Strange little bug there.

**Comment by Haxxer** [comment]
It's not a bug, it adds a buffer on top of the dice you would get.

**Comment by Haxxer** [comment]
I will add a setting in 1.0.6 that will make this an optional feature
