### ISSUE TITLE
[Bug] Behavior of Hit Points Recovery Fraction does not match the description

### ISSUE THREAD

**Issue by dev7355608** [fantasycalendar/FoundryVTT-RestRecovery#34]
**Describe the bug**
The description of *Hit Points Recovery Fraction* mentions that a fraction of missing HP are restored. But that is not true: it's a fraction of maximum HP that is restored.

**To Reproduce**
1. Create an actor with 10/20 HP.
2. Set *Hit Points Recovery Fraction* to *Half*.
3. Long rest.

Actor has 20/20 HP after the long rest.

**Expected behavior**
Depends on what is intended. If it should be based on missing, the actor should be at 15/20 HP after the long rest. The module *Long Rest Hit Dice Healing for D&D 5e* used missing HP, but, I think, recovery based on max HP makes much more sense. Why would healing be slower for a character that is more healthy? It's also potentially impossible to reach max HP without spending hit dice (at least in the implementation in the other module) if it's based on missing HP.

**Setup:**
 - Foundry Version: 9.255
 - System Version: 1.5.7

**Active modules:**
 - Rest Recovery
 - libwrapper

**Comment by Haxxer** [comment]
Thank you, I will adjust this in the next update.
