### ISSUE TITLE
[Feature Request] - API to configure settings to achieve per-location based settings

### ISSUE THREAD

**Issue by rinnocenti** [fantasycalendar/FoundryVTT-RestRecovery#36]
I would love to be able to create multiple long/short rest "sets" with different properties.
because I have a rest system that differs the amount of Hitdice recovered according to the quality of the place players rest.

a set did not recover a % of HP and an amount of hitdice different from other sets, so I could call (by macros) which one according to the place of rest, if it is in a rainy swamp or in the warm covers of an inn.

**Comment by Haxxer** [comment]
Hm, I like this idea. I think it would be best to have an API where you would be able to set this yourself, rather than make it explicit in the settings. That would mean that it would be up to you to manage which settings are set to what, but would certainly enable you to do this.

**Comment by Haxxer** [comment]
1.2.0 adds module profiles, which can be used to set multiple configurations of settings for your various locales.
