### ISSUE TITLE
Specify Long Rest spellslot restoration per spell level

### ISSUE THREAD

**Issue by Sinantrarion** [fantasycalendar/FoundryVTT-RestRecovery#38]
**Describe the solution you'd like**
Instead of just static spellslot restoration "one choice for all", provide separate fields for each spell slot- so that, for example, level 1 spell slots can use full spell slot restoration, level 2 half, and level 9- none(Generally to work with Epic Heroism rules and provided there idea, that "Spellslots higher than X don't restore on long rest unless full 8 hours").

**Comment by Haxxer** [comment]
I think this is outside of the scope of this module. It's far too niche and hard to implement in an appropriate way. Sorry.
