### ISSUE TITLE
[Feature Request] - Arcane Grimoire and Rest Recovery Edge Cases

### ISSUE THREAD

**Issue by marshallharck** [fantasycalendar/FoundryVTT-RestRecovery#39]
**Is your feature request related to a problem? Please describe.**
There is no bug, but so far there is no way to handle the Arcane Grimoire from Tasha's Cauldron of Everything, which gives an additional "spell" to Arcane Recovery's normal half-level round-up.

**Describe the solution you'd like**
Whichever way would be the easiest to tackle edge cases like these would be lovely, such as being able to edit either the base formula strings or note situational modifiers in the settings.

**Comment by Haxxer** [comment]
If the Arcane Recovery feature would use the "damage formula" on the item itself, I think that would be best. I'll see about implementing this in the future.
