### ISSUE TITLE
Add the ability to add a fixed amount (or perhaps a die) when short resting

### ISSUE THREAD

**Issue by turboraton** [fantasycalendar/FoundryVTT-RestRecovery#40]
In my campaign I reward my players with boons and blessings. One of them is that on a short rest they restore extra points equal to their proficiency bonus.

I hope this is not too difficult to add, it could be a die as well!

**Comment by Haxxer** [comment]
If you check the settings and select custom formula for HP/Hit Dice recovery, you can add their proficiency bonus that way.

**Comment by turboraton** [comment]
Amazing job!!!

**Comment by turboraton** [comment]
Sorry to bother you again but it seems that the custom formula only works
on long rests

**Comment by Haxxer** [comment]
Can't your players just add their proficiency bonus in the hit dice bonus roll window?

![image](https://user-images.githubusercontent.com/12858387/167003576-932b26c6-2b20-4b71-8bd8-ff74856b9349.png)
