### ISSUE TITLE
Tidy5e Sheet compatibility

### ISSUE THREAD

**Issue by lucaspicerni** [fantasycalendar/FoundryVTT-RestRecovery#44]
Make it possible to hide the "Configure resource recovery" option from Tidy5e Sheet, as this option already exists in it and is redundant.

![image](https://user-images.githubusercontent.com/95550238/170130476-4f2c0261-0b30-4b09-b997-5c1217fe4411.png)

**Comment by Haxxer** [comment]
This is to configure the formula for each one. Removing it would make this impossible.

**Comment by Haxxer** [comment]
Unless tidy5e has that embedded in the sheet already?

**Comment by lucaspicerni** [comment]
Not. In fact you are right. I hadn't noticed the formula field. I think this issue can be closed.
