### ISSUE TITLE
Long rest not recovering minimum 1 hit die

### ISSUE THREAD

**Issue by kaelad02** [fantasycalendar/FoundryVTT-RestRecovery#45]
**Describe the bug**
I have a level 1 character and when they long rest, they don't recover their 1 hit die. The rules state it's supposed to recover half, rounded down, minimum 1. I don't think the minimum 1 part is being accounted for. Not sure it's always that way or because of how I have it configured:

- checked "Enable long rest hit dice rolls"
- checked "Enable hit dice recovery before finishing long rest"
- checked "Enable hit dice max buffer"
- changed "Hit points recovery fraction" to `None`

**To Reproduce**

1. Open the module settings and modify the Long Rest settings ad described above
2. Select a level 1 PC, reduce their HP a bit and click the Long Rest button
3. Click on the Begin Long Rest button
4. Roll one hit die
5. Click the Rest button
6. Check the chat message, mentions recovering hit points but nothing about hit dice
7. Check the character sheet, it shows you have 0 hit dice

**Expected behavior**
It doesn't appear to honor the minimum 1 hit dice part. I should have seen 2 hit dice available because I checked "Enable hit dice max buffer". The chat message should have mentioned recovering 1 hit die. And I should have had 1 hit die left over after the rest, visible on the character sheet.

**Setup:**
 - Foundry Version: 9.269
 - System Version: 1.5.7
 - Rest Recovery Version: 1.2.0
 - Browser & version: Electron app

**Active modules:**
 - Advanced Macros
 - Compendium Browser
 - DF Chat Enhancements
 - DFreds Convenient Effects
 - Dice So Nice!
 - DAE
 - Item Macro
 - Item Piles
 - Chat Commands
 - libWrapper
 - More Hooks D&D5e
 - Rest Recovery
 - Sequencer
 - socketlib
 - Tidy UI - Game Settings
 - Token Action HUD
 - Universal Battlemap Importer
 - Warp Gate

**Comment by kaelad02** [comment]
No, they just have one.

If I start with the one hit die, and check "Enable hit dice recovery before finishing long rest"
and "Enable hit dice max buffer", then long resting should show that I have 2 available since I started with 1 and would get 1 for long resting. Even when I've used the hit die, then long rested again, I should gain 1 hit die but I'm still stuck at 0.

**Comment by Haxxer** [comment]
Right, I forgot about that part. I've identified the issue, and shall patch soon.

**Comment by Haxxer** [comment]
Fixed in 1.2.1
