### ISSUE TITLE
Trouble with the Wizard class using the localised module.

### ISSUE THREAD

**Issue by Padhiver** [fantasycalendar/FoundryVTT-RestRecovery#46]
**Describe the bug**
Using the module in French produces an error when trying to rest with the Wizard class in your character sheet.

**To Reproduce**
1. Go to character sheet and add wizard class with translated module.
2. Click on long rest.
3. Scroll down to console. 🤓 

**Expected behavior**
The rest window does not open at all, and it should appear! :')

**Screenshots**
![image](https://user-images.githubusercontent.com/80126915/171348792-d389156c-b492-44ac-9a92-b70754ee1b95.png)

**Setup:**
 - Foundry Version: Latest.
 - System Version: Latest
 - Item Piles Version: Latest, but for Rest recovery. 🤓 
 - Browser & version : I use client.

**Active modules:**
 - Rest Recovery
 - libwrapper
 - [insert more modules here]  - Tested with blank world with only Rest Recovery and dependenies.

**Additional context**
If I have time today I will give the translation an update!

**Comment by Haxxer** [comment]
It appears to work for me?

![image](https://user-images.githubusercontent.com/12858387/171407256-65f47725-2cc6-40cc-bf0e-0172890cfa32.png)

Even short rests work fine:

![image](https://user-images.githubusercontent.com/12858387/171407338-fd5dfecd-1f6b-4e2c-865a-536dc2b79953.png)
