### ISSUE TITLE
[Request] Food & Water: Consumed items are rolled as though targeting the character

### ISSUE THREAD

**Issue by ZhornLegacy** [fantasycalendar/FoundryVTT-RestRecovery#49]
For food and drinks that have been set up to offer buffs or bonus healing.
Think things like a goodberry, of the treats made with the Chef feat.
I know I've seen a few games with homebrewed food and drink with additional effects.
Before tthis module made tracking food/water easier, I was incentivising players to invest in that by having water and rations boost total healing from rests by +1d4 each.

**Comment by Haxxer** [comment]
I would appreciate if you could use the template for feature requests instead :)

![image](https://user-images.githubusercontent.com/12858387/171411807-297b7dfc-bd4b-4354-bdda-ab688b4f8b7e.png)

**Comment by Haxxer** [comment]
I looked into this, and I'm afraid it becomes harder with different levels of automation. I would recommend that you instead use the items manually though the character sheet, as any consumable items will be counted towards daily food and water.
