### ISSUE TITLE
[Bug] Exhaustion effects are being applied multiple times

### ISSUE THREAD

**Issue by rinnocenti** [fantasycalendar/FoundryVTT-RestRecovery#53]
**Describe the bug**
gaining exhaustion from food, after it starts to recover the program breaks down and adds several conditions

**To Reproduce**
See a video

**Expected behavior**
the program, by selecting only the DF condition module, should add only the DF conditions instead of applying the DF and the conditions of the module, and also apply multiple conditions and conditions that do not coincide with what is informed.

**Screenshots**
See a video
[https://1drv.ms/v/s!AqWyVKHNPqK_pSEUKKqc9JYHSQle?e=wMje3Q](https://1drv.ms/v/s!AqWyVKHNPqK_pSEUKKqc9JYHSQle?e=wMje3Q)

**Setup:**
 - Foundry Version: [e.g. 9.269]
 - System Version: [e.g. DND5e 1.6.1]
 - Rest Recovery Version: [e.g. 1.2.2]
 - Browser & version [in App Foundry]

**Active modules:**
 - Rest Recovery
 - libwrapper
 -in video has many, but, whit only dependent mdules, still happens

**Comment by Haxxer** [comment]
I see that you get errors, could you please open your console and look for any red text and take a screenshot?

**Comment by rinnocenti** [comment]
![image](https://user-images.githubusercontent.com/3178127/171789791-8e6b64f3-9f38-4bfc-aa4f-5c4e337fa112.png)

**Comment by Haxxer** [comment]
Anything before that? Cause I only see `dnd5e-helpers` at the top, which is another module?

**Comment by rinnocenti** [comment]
no, but this error does not appear without the module, and the bug continues, the exhaustion line errors 177 yes.
Apparently the error is in the way it is treating exhaustions, when the module tries to create the item with the effect.

The smooth error only appears when the module tries to create the item in the character (caused by the exhaustion error called by the module).

**Comment by Haxxer** [comment]
@rinnocenti 
Could you contact me on discord, and we could discuss things there? Wasp#2005

**Comment by rinnocenti** [comment]
Sorry, I just saw this message today.
I will contact you on discord
