### ISSUE TITLE
[Request] Add resource recovery setting for short rests

### ISSUE THREAD

**Issue by tpont** [fantasycalendar/FoundryVTT-RestRecovery#56]
**Is your feature request related to a problem? Please describe.**
For now, when taking a long rest only gives back the amount set for long rests to ressources reloading on short rest (half or quarter)
It still works normally when taking a short rest.

**Describe the solution you'd like**
Long rests can fully recharge ressources and feats recharging on short rests.

**Describe alternatives you've considered**
Add an option for half/quarter like the others, or just make it recharge fully

**Additional context**

**Comment by Haxxer** [comment]
Could you please rephrase your question? I don't understand.

**Comment by tpont** [comment]
Here i have a ressource set to recover in short rests. I've set the recovery of long rests on a quarter for everything (i don't see any option for short rests recovery)

![Capture d’écran 2022-06-04 174914](https://user-images.githubusercontent.com/9135225/172013593-15c3fe5d-860c-473d-987a-9caec790c442.png)
![Capture d’écran 2022-06-04 174931](https://user-images.githubusercontent.com/9135225/172013596-cb92b80e-dc4d-44fe-8890-0c1a5eac4026.png)

And after a long rest it only recovered 1/4, like a long rest one. What i'm asking if it should recover all its charges on long and short rests.

**Comment by Haxxer** [comment]
Okay, thank you for clarifying, I will add short rest resource recovery as a setting in the next update.
