### ISSUE TITLE
[Suggestion] Add a visual limit count to short rests

### ISSUE THREAD

**Issue by Fridan99** [fantasycalendar/FoundryVTT-RestRecovery#58]
**Is your feature request related to a problem? Please describe.**
NO.

**Describe the solution you'd like**
What i suggest is that each character can see how many short rest he/she has left, when using the **limit short rest** variant. 

Maybe implement it in resource.primary, or be able to choose where (resource.secondary, terciary.....)

The problem is that if a game lasts several sessions, probably in the 2nd or 3rd game each player will not remember if he has 2 or 1 short rest left. 

It is not really a problem in itself, since with the limit they can never exceed the maximum allowed. But it is rather a problem for each player to better manage his short rest..... 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Haxxer** [comment]
I will add text in the short rest UI when this setting is enabled.
