### ISSUE TITLE
[BUG] Food and water tracker not working

### ISSUE THREAD

**Issue by HubberGrabber** [fantasycalendar/FoundryVTT-RestRecovery#59]
**Describe the bug**
When attempting a long rest using ration and water skin does not reduce the counter needed to avoid a level of exhaution

**To Reproduce**
1. Go to character menu
2. Click on Long rest
3. Scroll down to rations and use a ration

**Expected behavior**
Using a ration should reduce the needed amount of rations to avoid a level of exhastion

**Screenshots**

**Setup:**
 - Foundry Version: 9
 - System Version: Pokemon D&D 5e
 - Rest Recovery Version:1.2.2

**Active modules:**
about time
advance macro
better rolls for 5e
Calander / Weather
Character actions list DnD5e
Combat utility belt
Crash's Tracking and Training 5e
Day night cycle
Dfreds Droppables
Dynamic effectis using active effects
Easy not
FXMaster
GM notes
Health Estimate
Intitive Double Click
Item Container
Item Macro
Less fog
Lib - color setting
Libwrapper
Midi QOL
Pokemon 5e
Quick Notes
Simple Calander
scoketlib
Split journal
The furnace
Weather Control
Windows Control

**Comment by Haxxer** [comment]
Is the ration configured to be a consumable?

**Comment by Haxxer** [comment]
@HubberGrabber 

![image](https://user-images.githubusercontent.com/12858387/172349005-16be6b1d-c499-47b9-afc4-8c39b4deded8.png)

**Comment by HubberGrabber** [comment]
It was not, are they suppose to update automatcally if they are pull from the srd? As there no mention of having to set those manually.
