### ISSUE TITLE
[BUG] No auto roll of HD and no animation of HP recovery

### ISSUE THREAD

**Issue by ctbritt** [fantasycalendar/FoundryVTT-RestRecovery#60]
**Describe the bug**
The auto roll button on both long and short rest does nothing. I also don't see the animation previewing how many HP the player will get back anymore. 

**To Reproduce**
1. Attempt to take a long or short rest
2. Click autoroll to roll HD
3. Nothing happens

**Expected behavior**
HD are auto-rolled and an little animation shows on the HP bar how many HP you can expect to get back. 

**Screenshots**
![CleanShot 2022-06-09 at 10 29 25](https://user-images.githubusercontent.com/4516034/172872242-8e3da5a5-3c49-4bb6-a561-4078d146f626.gif)

**Setup:**
 - Foundry Version: 9.269
 - System Version: DnD5e 1.6.1
 - Rest Recovery Version: 1.2.3
 - Browser & version Google Chrome 02.0.5005.61 (Official Build) (arm64)

**Active modules:**
 - Rest Recovery
 - libwrapper

**Additional context**
Exporting module profile comes back as "undefined" every time.

**Comment by Haxxer** [comment]
Fixed in 1.2.4
