### ISSUE TITLE
[BUG] Rescource consumption error

### ISSUE THREAD

**Issue by krysztalzg** [fantasycalendar/FoundryVTT-RestRecovery#61]
**Describe the bug**
When using both Rest Recovery and BetterRolls items with resource consumption are not working properly in DnD 5e version 1.6.2.

**Resolve the bug**
In line 25121 of the script there's logic for resource usage, that in dnd 1.6 was change to be an array not a function. 
Not to mention that this line compares foundry version 9.269 to dnd 5e version 1.5.7, which makes no sense.
```const resourceUpdates = isNewerVersion(game.version, "1.5.7") ? {} : []; // Consume Recharge```

**To Reproduce**
1. Go to PC character sheet.
2. Click on weapon with resource consumption, eg. bow with arrows
3. See error

**Expected behavior**
Items with resource consumption should roll properly.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/6009785/172953254-6ce3416f-b291-4f10-b955-d16467227690.png)

**Setup:**
 - Foundry Version: 9.269
 - System Version: 1.6.2
 - Rest Recovery Version: 1.2.3
 - Browser & version: FoundryVTT app

**Active modules:**
 - Rest Recovery
 - libwrapper 1.12.5.0
 - Better Rolls 1.7.2 
 - Midi QoL 0.9.57

**Comment by Haxxer** [comment]
Thank you for pointing out my mistake, fixed in 1.2.4
