### ISSUE TITLE
[BUG] auto roll only rolls once, doesn't roll song of rest

### ISSUE THREAD

**Issue by MrPotatoZed** [fantasycalendar/FoundryVTT-RestRecovery#63]
With only rest recovery and libwrapper active pressing the auto roll button only rolls one hit dice no matter how little hp is left and how many hit dice are available. Additionally, no song of rest is rolled with auto-roll. Pressing roll also results in one hit dice roll but does cause song of rest to be rolled; the behavior pressing roll button is as expected. Tested using default config with quick roll hit dice active (same results with quick roll deactivated).

Noteworthy that in my testing today I thought I had seen the expected behavior once i.e. auto roll function causing multiple hit dice rolls, but I cannot replicate that correct behavior even after ctrl+f5 and restarting the server. It is possible that I was just seeing hit dice and song of rest dice rolls. In that instance it did not keep rolling until hp was full, but instead stopped at about 59 out of 71 hp. 

No errors visible in console. Rest recovery 1.2.5, libwrapper 1.12.5.0, v 9.269, 5e 1.6.2. Tested on firefox and chrome with windows 10. 

 Video:
![restrecovery](https://user-images.githubusercontent.com/85974617/173106760-7d7b4b0d-c922-4c78-a47d-761afe5b623a.gif)

**Comment by Haxxer** [comment]
Fixed in 1.2.7

**Comment by MrPotatoZed** [comment]
Hate to be the voice of the wack-a-mole but in 1.2.8 the auto roll button isn't doing anything again. Not a huge deal as I can just disable it for now to avoid confusion but wanted to let you know. Was seeing the same thing in 1.2.7 (and I think 1.2.6?). Thanks for working on what seems like a tough problem. 

Tested in a clean world with only rest recovery and libwrapper active. v 9.269, 5e 1.6.2., hosted on forge.
![RRauto](https://user-images.githubusercontent.com/85974617/173878699-f8a3239c-370c-41c0-a636-9a3fed3df3fc.gif)

**Comment by Haxxer** [comment]
@MrPotatoZed Thanks, I missed a few things. I made some structural changes overall to fix this, could you download the test version and check it out?

https://raw.githubusercontent.com/fantasycalendar/FoundryVTT-RestRecovery/next/module.json

**Comment by MrPotatoZed** [comment]
Success; take that mole! Works great.
