### ISSUE TITLE
[Request] Maximum Hit Die spent per Short Rest

### ISSUE THREAD

**Issue by NdranC** [fantasycalendar/FoundryVTT-RestRecovery#65]
In the spirit of having Long/Short rests grant less resource recovery, I think there should be a maximum Hit Die per Short rest option. This would make people not be able to use all their hit die in a single short rest.

It would be ideal if the amount of Hit Die could be configured with a formula or at the very least, fractions like 1/4, 1/3, 1/2.

BTW, thanks for the work on this mod. It single-handedly addresses a lot of the issues I have with the 5e resting system in a way that could only be comfortably done in a VTT.

**Comment by Haxxer** [comment]
Added in 1.2.11
