### ISSUE TITLE
[Request] A5E support

### ISSUE THREAD

**Issue by PsykotikDragon** [fantasycalendar/FoundryVTT-RestRecovery#68]
In LevelUp: Advanced 5e (A5E) tracking rest, supply (rations), & recovery is more important than in original 5e (O5E). There's physical & mental strain (exhaustion & strife, respectively) that happen if you don't consume food & water (a supply) per day. All this can, OFC, be tracked manually, but having the rest recovery module pull that up & account for supply automatically in this system, like it does for O5E, would be awesome.

A lot of the same terminology/scores/stats are the same as O5E as it's fully compatible with it, but from what I understand the underlying system runs differently so not all of the modules out there for O5E are compatible as they're looking at slightly different names, abilities, sheet locations, etc.
Thanks for the consideration & keep up the awesome work! I look forward to seeing more awesome stuff from you!

**Comment by Haxxer** [comment]
Could you link to the rules surrounding this system? Is it available online anywhere?

**Comment by PsykotikDragon** [comment]
> Could you link to the rules surrounding this system (specifically food & water)? Is it available online anywhere?

At the bottom of the conditions page is the info on tracked conditions, fatigued & exhausted
https://a5e.tools/rules/conditions

**Comment by Haxxer** [comment]
Yeah it different from 5e, so I'd probably recommend forking this module into its own version. Talk to the guys over at the A5E discord and maybe someone'll step up :)
