### ISSUE TITLE
I'd like to disable the "Configure Resource Recovery" on the character sheet.

### ISSUE THREAD

**Issue by LtDerek** [fantasycalendar/FoundryVTT-RestRecovery#69]
I find it much to large and distracting, and my character sheet already has the short rest/long rest functionality build in.

Could we get a way to disable it in the options?

**Comment by Haxxer** [comment]
Can your sheet also configure a formula for the resource recovery? I'll add a setting, but there's a reason it exists

**Comment by Haxxer** [comment]
Closed, as there has been no response.

**Comment by LtDerek** [comment]
Ah, I didn't read this properly the first time and missed the question. My sheet doesn't let my configure specific recoveries, it can just choose if the resource is refilled on a short/long rest.
