### ISSUE TITLE
New formula

### ISSUE THREAD

**Issue by Dalkan75** [fantasycalendar/FoundryVTT-RestRecovery#70]
Hello,
this module is beautiful, I really like it and congratulations for the hard work.

I come to my request, for the long rest I use a personal formula that restores HP:
Double of Character level + Constitution bonus
Example: Second level warrior with Costitution 16 (bonus +3) gains = 7 HP (4 for the double level + 3 for the bonus)

Which formula could I use?
Thank you very much

Robert

PS: sorry for my bad english :(

**Comment by Dalkan75** [comment]
I try
@class.levels*2+@abilities.con
but does'nt work
where i'm wrong?

Thank you

Best Regards

Robert

**Comment by Haxxer** [comment]
`@classes.levels*2 + @abilities.con.mod` will work, I believe.

In the future, please avoid using github tickets as a means to ask questions about the module. The Foundry VTT Discord server can help yuo a lot faster.

**Comment by Dalkan75** [comment]
I'm sorry :(
and thank you
anyway, @classes.levels*2 does'nt work
@abilities.con.mod do it

thank you and best regards

Robert

**Comment by Haxxer** [comment]
Try `@details.level`, that should work.

**Comment by Dalkan75** [comment]
GOOD! It' Work!
Thank you :) 
You are the best!

Have a nice day!
Best Regards

Roberto
