### ISSUE TITLE
Option to retain cancel button after hit dice have been used

### ISSUE THREAD

**Issue by SDoehren** [fantasycalendar/FoundryVTT-RestRecovery#71]
**Is your feature request related to a problem? Please describe.**
I use a special rest called "breather" where players can use short rest hit dice but gain no other benefits.  This is harder when the cancel rest button disappears.

**Describe the solution you'd like**
The option to keep the cancel button after hit dice have been used.

**Comment by Haxxer** [comment]
Closed, as there has not been a response.
