### ISSUE TITLE
[BUG] Cras in Module

### ISSUE THREAD

**Issue by rinnocenti** [fantasycalendar/FoundryVTT-RestRecovery#72]
**Describe the bug**
I have a problem with the module, I created a profile but when I saved it, it reset the foundry and then deleted my right sidebar.
I restarted the foundry and now it tries to find the profile I created, it doesn't find it (it gives an error) but it also doesn't let me enter the settings anymore, because it doesn't appear in the data, but even so the check asks for the profile.

I don't know how to reproduce it, when I tried to export the .json it came empty, but if I use the "getAllProfilesData()" function, my other profiles appear but the one I created doesn't appear, and even so the module asks for it.

I record a video:
https://drive.google.com/file/d/1Qwb-XPvbIV0b6BVOK7LnzxgKcfK2PhHm/view?usp=sharing
https://drive.google.com/file/d/1XcLSigfFOdHyGV94Awa68BRwp8li4qMA/view?usp=sharing

PS:
![image](https://user-images.githubusercontent.com/3178127/176819720-14ad10e3-902e-44f3-b27c-f397afb318e5.png)
![image](https://user-images.githubusercontent.com/3178127/176820035-0d29b620-01cb-4b7b-8781-1d4d1bab9b7f.png)

In the video the dropdawn doesn't appear, but it doesn't change, when I remove an item and save it, it doesn't appear on the first opening, but as soon as I open it again it returns.

The same goes when I create an item, at first it appears then if I open it again it disappears and shows the error

the strange thing is that I managed to create the first 4 profile then I can't anymore.

**Comment by Haxxer** [comment]
Hi, could you run this code in the console, create a .txt file, and upload it here?

```js
JSON.stringify(game.settings.get("rest-recovery", "module-profiles"))
```

**Comment by rinnocenti** [comment]
[rest.txt](https://github.com/fantasycalendar/FoundryVTT-RestRecovery/files/9081490/rest.txt)

**Comment by rinnocenti** [comment]
![image](https://user-images.githubusercontent.com/3178127/198899015-2e19dc95-bdc8-4c06-8d9b-6ca590eea858.png)
I'm trying to create profiles in version V10, but I can't, it doesn't save any profiles.

**Comment by rinnocenti** [comment]
![image](https://user-images.githubusercontent.com/3178127/198899075-49b474b4-2d92-4e96-b1ed-e527e40688f4.png)

I can create the profiles, but none of them are saved.

**Comment by Haxxer** [comment]
Could you message me on the foundry discord instead? Easier to have a conversation there.
