### ISSUE TITLE
[BUG] Exhaustion gets applied 2 times, and then deleted

### ISSUE THREAD

**Issue by Kurokasa** [fantasycalendar/FoundryVTT-RestRecovery#75]
Hi, first of all thx for the amazing work. I will never run DnD without this module again :D

When a resting without water or food the module seems to apply the active effect for exhaustion twice and throws a few errors. I tried the active effects with CUB or to disable the active effects via the Long Rest tab (not sure if it is even supposed to deactivate DAE for the food aswell) but it still does the same thing. It also tries to jump from exhaustion lv1 to lv3 when no food or water is present, but still fails in the same way.
Iam not sure if it comes from this, but i know that CUB added a feature that removes other Exhaustion levels when a new one is added and some modules like Tidy5eSheet seems to have problems with that aswell. (or atleast i think it came from CUB)

![Screenshot 2022-07-15 000107](https://user-images.githubusercontent.com/102412559/179097572-d972ebe3-a4d2-49c7-8251-20129fb66eff.jpg)

**Setup:**
 - Foundry Version: 9.269
 - System Version: DND5e 1.6.3
 - Rest Recovery Version: 1.2.11
 - Browser & version: Forge Client, Chrome 103.0.5060.114

**Active modules:**
Active-Auras v;
Active Token Effects v;
Advanced Macros v;
Ambiences Volume 1 - Michael Ghelfi v;
Argon - Combat HUD v;
Automated Animations v;
Automated Evocations - Companion Manager v;
Award XP v;
Better Roofs v;
Changelogs & Conflicts v;
Combat Utility Belt v;
Compendium Browser v;
Compendium Folders v;
Conditional Visibility v;
Cozy Maps v;
Crafting Compendium (Shared Compendiums) v;
Custom Token Animations v;
D&D5e Character Monitor v;
D&D Beyond Importer v;
Dice So Nice! v;
Dice Tray v;
DnD5e Helpers v;
Dynamic Active Effects SRD v;
Dynamic effects using Active Effects v;
Filepicker + v;
Forien's Unidentified Items v;
FXMaster v;
Give item to another player v;
Image Context v;
Item Macro v;
Item Piles v;
JB2A - Patreon Complete Collection v;
Kuro-CoreData (Shared Compendiums) v;
lib - Color Settings v;
Library: Scene Packer v;
libWrapper v0;
LiveKit AVClient v;
LootsheetNPC5e v;
Lordu's Custom Dice for Dice So Nice v;
Maestro v;
Magic Items v;
Midi QOL v;
Midi SRD v;
Minimal UI v;
Monk's Active Tile Triggers v;
Monk's Enhanced Journal v;
Monk's Little Details v;
Monk's Scene Navigation v;
Monk's TokenBar v;
Multilevel Tokens v;
Perfect Vision v;
Pings v;
Polyglot v;
PopOut! v;
Rest Recovery for 5E v;
Select tool everywhere v;
Sequencer v;
Settings Extender v;
Shared - Data (Shared Compendiums) v;
Show Art With Credits v;
Simple Calendar v;
SmallTime v;
Smart Target v;
socketlib v;
Temporary Effects as Token Statuses v;
The Forge: More Awesomeness v;
Tidy5e Sheet v;
Tidy UI - Game Settings v;
Times Up v;
Token Attacher v;
Tokenizer v;
Token Magic FX v;
Token Z v;
Warp Gate v;
Weather Blocker v;

**Comment by Haxxer** [comment]
Could you please use Find The Culprit to try to find the conflict?

**Comment by Kurokasa** [comment]
I tested it and it seems the already mentioned Tidy5e Sheet is the Culprit for the doubling the active effects. It seems appling 2 levels of exhaustion after not drinking for 2 days comes for your module or even is intended? When i rested him up and then didnt eat or drink on the first day he got 1 and on the second day added 2 exhaustion levels. I think this is wrong but iam not sure :D he has enogh con so food isnt an issue for a few days.
I also updated to the latest version of your module (sry for not doing so in the first place >.<)
![Screenshot 2022-07-15 005032](https://user-images.githubusercontent.com/102412559/179101681-8fd50b39-945e-41f9-962d-efbd519ddb99.jpg)

**Comment by Haxxer** [comment]
Could you disable the exhaustion automation in Tidy5e's settings then? If that doesn't fix the errors, then I will investigate it.

As for the double exhaustion, I'm pretty sure that it is intended to work that way:

According to this:

https://roll20.net/compendium/dnd5e/Rules:The%20Environment#toc_7

"If the character already has one or more levels of [Exhaustion](https://roll20.net/compendium/dnd5e/Conditions#h-Exhaustion), the character takes two levels in either case."

So that adds two. Normally you'd also lose one, but according to the exhaustion rules:

https://roll20.net/compendium/dnd5e/Conditions#h-Exhaustion

"Finishing a Long Rest reduces a creature’s exhaustion level by 1, provided that the creature has also ingested some food and drink."

Means you do not reduce 1, and instead gain 2.

**Comment by Kurokasa** [comment]
Sry, i just edited my comment ^^
Yeah disabling the automation in Tidy5e Sheet "fixed" it.
Perfect, so it is intended and i just dont know my rules :D 

What about this error message? (Everything still works)
![Screenshot 2022-07-15 005450](https://user-images.githubusercontent.com/102412559/179114769-8fedbda4-fd1d-49d0-b393-755988e3c7cb.jpg)

**Comment by Haxxer** [comment]
Does that error always happen? Does it happen with only Rest Recovery (and libwrapper) enabled?

**Comment by Kurokasa** [comment]
Oh, it happens without Rest Recovery :D 
Thx for your wonderful and instant help 10/10 will get confused about bugs again :)

**Comment by Haxxer** [comment]
Cool - glad everything works
