### ISSUE TITLE
[Request] Recovering half of your spells on a long rest and or creation of custom Arcane/Natural Recovery like features

### ISSUE THREAD

**Issue by CannibalPizza** [fantasycalendar/FoundryVTT-RestRecovery#77]
**Is your feature request related to a problem? Please describe.**
I wanted to have spellcasters recover spell slots like with Arcane/Natural Recovery on a short/long rest using this module's UI for those abilities.

**Describe the solution you'd like**
I think an option to allow customizable Arcane/Natural Recovery style spell recovery on a short/long rest would be best. This could be a general option that allows spell recovery for all spellcasting classes and I believe could avoid having to directly implement this style of ability/feature for every class including custom classes. It could function exactly as arcane and natural recovery do but as a toggleable option in the configuration settings for every PC with a spellcasting feature in place of full spell slot recovery.

**Describe alternatives you've considered**
If a general Arcane/Natural Recovery like feature as a toggleable option for all spellcasters is not possible, this functionality could be replicated by allowing the UI elements for Arcane/Natural recovery work for features structured the same way as those features. For example, if I made a general Spell Recovery feature for every class that could use the Arcane/Natural recovery style UI.

**Additional context**
- Add a "Spell recovery method" option in the Long Rest and Short Rest tabs which allow for the Arcane/Natural Recovery style spell recovery
![image](https://user-images.githubusercontent.com/90525162/181918227-acbcc334-c8b1-4a19-88e6-812d797bc4f3.png)

- What I mean by "a general Spell Recovery feature for every class" which is "structured the same way as those features":
![image](https://user-images.githubusercontent.com/90525162/181918038-19f3fdbe-51fb-4f8b-b99c-0636484a2a11.png)
- Add a button which allows you to add additional custom features to work the same way as Arcane/Natural Recovery
![image](https://user-images.githubusercontent.com/90525162/181918325-c4b5bf4a-059a-41ad-b220-da22ab478933.png)

**Comment by Haxxer** [comment]
@CannibalPizza How would you expect this to work in conjunction with Arcane Recovery and such?

**Comment by CannibalPizza** [comment]
@Haxxer I think you could just make a feature which works exactly like Arcane/Natural Recovery which can be put on whatever spellcasting class and have it appear underneath Arcane/Natural recovery on the same page.

**Comment by Haxxer** [comment]
Added in 1.4.0
