### ISSUE TITLE
Accepting other items as food or water than ration and waterskin from SRD

### ISSUE THREAD

**Issue by davelacorneille** [fantasycalendar/FoundryVTT-RestRecovery#78]
Would be nice if we can drop other items for food or water instead of Ration and waterskin SRD.

Example: flour, goat, chicken, ration (from D&D Beyond importer).

Display in the chat what item was used for food and water as a verification of what was used.

**Comment by Haxxer** [comment]
You can configure individual items as food. Open the item's details and configure it accordingly.

**Comment by davelacorneille** [comment]
Thanks!  I just find out that you need to set it to "consumable" also.

**Comment by Haxxer** [comment]
Closing, because module already supports this functionality.
