### ISSUE TITLE
Song of rest

### ISSUE THREAD

**Issue by St-Toha** [fantasycalendar/FoundryVTT-RestRecovery#79]
Can you please explain to me how to make bards song of rest to work automatically with this module? I have a bard in a party but it does nothing and there is no useful information on wiki page. I`m losing my mind at this point, pls explain

**Comment by Haxxer** [comment]
Does the character have the feature named "Song of Rest"?

**Comment by St-Toha** [comment]
> Does the character have the feature named "Song of Rest"?

yes

**Comment by Haxxer** [comment]
Github tickets is less for support and more for requests and bug reports. Could you please tag me in the Foundry discord server? I'm Wasp#2005.
