### ISSUE TITLE
Hit Dice roll produce negative HP results ....

### ISSUE THREAD

**Issue by R0TEAM** [fantasycalendar/FoundryVTT-RestRecovery#80]
**Describe the bug**
If the CON mod negative .. the roll can produce -1 or even more negative HP change ... in the Rules it say's it is at last "0" ..

Regards

**Comment by Haxxer** [comment]
This is actually default behavior in D&D 5e. I can patch it through Rest Recovery, but please create a bug ticket on the github repo for the D&D 5e system.

https://github.com/foundryvtt/dnd5e

**Comment by Haxxer** [comment]
Up to D&D5e to fix:

https://github.com/foundryvtt/dnd5e/issues/1769
