### ISSUE TITLE
[BUG/FEATURE REQUEST?] Short Rest recovery doesn't work with Pact Magic 5e

### ISSUE THREAD

**Issue by NdranC** [fantasycalendar/FoundryVTT-RestRecovery#81]
As far as I can tell there is no setting for Pact Magic spells for short rest recovery. Despite of all other settings being set to "Quarter" if a warlock takes a short rest, they automatically recover all their pact magic spell slots.

I just realized this might not be a bug and instead it's just a lack of feature support. I'll leave it here anyway just in case.

**Comment by Haxxer** [comment]
It is indeed not a bug as pact spell slots are not considered spell slots in the same way normal spell slots are. If you wish to have a feature in the module to cover this use case, please create a feature request.
