### ISSUE TITLE
[BUG] Black Blood Recovery doesn't seem to work(At least on Forgevtt)

### ISSUE THREAD

**Issue by Sinantrarion** [fantasycalendar/FoundryVTT-RestRecovery#83]
**Describe the bug**
While testing for Black Blood Recovery started being interested if it actually works. It doesn't show in the roll in chat that it rerolls 1s, and at first the amount of them seemed smaller. However, decided to roll a large scale testing, 100 rolls of Barbarian's hit dice with +0 con, so that only dice results show up, with and without it in the character sheet(so 100 for with and 100 without). Apart from the fact that without the feature rolled a lower average score, no particular dependency noticed, and not sure if it actually works. 

**To Reproduce**
1. Add Black Blood Recovery to character sheet
2. Roll hit dice
3. No Rerolling happening

**Expected behavior**
The formula for rolling hit dice should include r<2 to reroll the values and actually show the result being rerolled. 

**Screenshots**
![image](https://user-images.githubusercontent.com/49957461/186221809-0848a3a1-f0c6-4c32-91bf-ba40d6464405.png)
![image](https://user-images.githubusercontent.com/49957461/186221846-b719f968-4d10-4dea-ae7f-e2dc84c65aa4.png)

**Setup:**
 - Foundry Version: [9.269]
 - System Version: [DND5e 1.6.3]
 - Rest Recovery Version: [1.2.12]
 - Browser & version [Mozilla Firefox 103.0.2]

**Active modules:**
 - Rest Recovery
 - libwrapper
 - (Tried with both a lot of others and none others than the mentioned)

**Comment by Haxxer** [comment]
Is the feature on your character named exactly as the setting in the localisation settings?

**Comment by Haxxer** [comment]
Fixed in 1.3.0 (Foundry V10 only)
