### ISSUE TITLE
[Request] Hit die recovery changes based on resting in heavy armor or not

### ISSUE THREAD

**Issue by YepJared** [fantasycalendar/FoundryVTT-RestRecovery#86]
**Is your feature request related to a problem? Please describe.**
It would be nice if there was an option to enable the Xanathar's resting rules relevant to heavy armor so as to properly tax PC resources. Relevant snippet below:

"Sleeping in light armor has no adverse effect on the wearer, but sleeping in medium or heavy armor makes it difficult to recover fully during a long rest. When you finish a long rest during which you slept in medium or heavy armor, you regain only one quarter of your spent Hit Dice (minimum of one die). If you have any levels of exhaustion, the rest doesn’t reduce your exhaustion level."

**Describe the solution you'd like**
I'd like for there to be a checkbox where you can enable the above rules and then it would be a nice to have if you could define custom formula for hit die recovery when users are wearing heavy armor. I know some dm's also like to be able to have characters that long rest in heavy armor gain exhaustion (but I personally don't play with that rule). 

**Describe alternatives you've considered**
Alternatives include:
- Making this the default rule
- Just having options to specify recovery with heavy armor equipped
- Adding more functionality to customize based on light, medium or heavy armor equipped instead of just heavy.

**Additional context**
I love the automation this module provides and would love if I could incorporate this rule to more consistently tax my player's resources.

**Comment by Haxxer** [comment]
How do you picture this being displayed on the long rest UI?

**Comment by YepJared** [comment]
By Long Rest UI, do you mean the pop-up that appears when the Long rest button is clicked or in the settings menu?

In the pop-up that appears, I would imagine that there would either be a warning that would note something along the lines of "You have *armor_type_setting* armor equipped. You will only recover *armor_hit_die_recovery_setting* of your hit die. Exhaustion points will not be reduced" With the last setting being based on if the exhaustion not recover setting was ticked off. 

There could also be an additional line with a checkbox that asks "Rest without armor on?" (similar to the Is New Day prompt) that if checked will do hit die and exhaustion recovery normally but will adjust the chat message that is produced to highlight "X Character chose to long rest without their armor equipped" in some prominent way (maybe bolding) so that the DM/GM can easily see this fact and account for it.

**Comment by Haxxer** [comment]
@YepJared 

Something like this?

![image](https://user-images.githubusercontent.com/12858387/189554531-1d008dde-033a-45c4-b5d3-215a72fb4a21.png)

**Comment by YepJared** [comment]
Honestly that is some pretty amazing work and almost exactly how I imagined it. The only thing I would change would be to have the default text on that first image ask "Remove heavy armor during long rest" and essentially reverse the functionality there. 

The only reason I think that method is preferable is:
1. I feel like the character needs to take some sort of action to remove armor and so this should be mirrored by the player needing to make a concrete choice to make the removal. 
2. Ideally, this option wouldn't appear if the character doesn't have heavy armor equipped in the first place. This means that players that don't wear heavy armor won't see this dialogue and so if they choose to wear heavy armor eventually, the indicator should prompt them to think about this new facet of the game.

But seriously. Amazing work! This is awesome!

**Comment by Haxxer** [comment]
1. Fair.
2. That is how it works, I only include that option if they have heavy armor currently equipped.

**Comment by Haxxer** [comment]
Added in 1.3.2
