### ISSUE TITLE
[Request] Put food and water into the normal resting tab

### ISSUE THREAD

**Issue by Krigsmaskine** [fantasycalendar/FoundryVTT-RestRecovery#91]
**Is your feature request related to a problem? Please describe.**
My players 100% miss the tab for food and water consumption without me prompting so far after around 20-30 sessions. I'm aware that this is concerning for the future of humanity, particularly as it has a red exclamation mark that glows, but such is life.

**Describe the solution you'd like**
Instead of having a separate tab for the food and water, can it just be on the same prompt as the one that asks if it's a new day

**Comment by Haxxer** [comment]
That would make for a far more cluttered UI than I would like - perhaps I could add a warning that pops up before you finish the rest that asks you if you really want to finish the day without eating?

**Comment by Krigsmaskine** [comment]
Honestly I think they'd just keep forgetting but now have to click an extra time. :p It'd save me running the Exhaustion reset macro, but that's about it. 

I don't think it'd clutter the UI much at all, there's only like one or two lines core if not for rest recovery's own warning, here's a quick and dirty mockup. Honestly if we're at the ease of UI, I'd probably like a setting to have the "food source/water source" checkboxes checked by default, party likes hanging around taverns most of the time.

![image](https://user-images.githubusercontent.com/39592771/191148191-2cee6592-4c81-4a41-b265-2619c1a24438.png)

**Comment by Haxxer** [comment]
Added in 1.4.0
