### ISSUE TITLE
[BUG] Long Rest not using food / water items, resources not recharging

### ISSUE THREAD

**Issue by Tatonker** [fantasycalendar/FoundryVTT-RestRecovery#96]
**Describe the bug**
With Exhaustion checking enabled and adding Food / Water for the Long Rest check, the rest does not appear to trigger any item consumption or resource recharging (exhaustion is NOT added). If food and water are NOT added, the exhaustion tracking kicks in and adds the appropriate exhaustion level.

**To Reproduce**
1. Click on the token's 'Long Rest' button (default 5e character sheet)
2. Click on 'Food/Water' and add the necessary food / water options
3. Click on 'Begin Long Rest' and then 'Finish Long Rest'.

**Expected behavior**
Water and Rations (correctly set up as consumable Water / Food items) are not used and do not have a charge used up. Resources that recharge on Long Rest are not recharged. Error message appears in the chat log.

**Screenshots**
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
[Detected 1 package: rest-recovery]
    at module.js:17174:78
    at Array.findIndex (<anonymous>)
    at RestWorkflow._handleFoodAndWaterItems (module.js:17174:33)
    at 🎁CONFIG.Actor.documentClass.prototype._rest#rest-recovery (module.js:21490:45)
```

**Setup:**
 - Foundry Version: 10.286
 - System Version: DND5e 2.0.3
 - Rest Recovery Version: 1.3.4
 - Browser & version: Google Chrome 105.0.5195.127 

**Active modules:**
 - Rest Recovery
 - Libwrapper 1.12.10.0
 - Find the Culprit 1.4.5

**Additional context**

**Comment by Haxxer** [comment]
Fixed in 1.3.5
