### ISSUE TITLE
[BUG] Short rest feature automation using deprecated DataModel

### ISSUE THREAD

**Issue by TlMcook** [fantasycalendar/FoundryVTT-RestRecovery#97]
**Describe the bug**
Short rest automation for features such as: Song of Rest, the Chef Feat, and Hit Die Bonus, do not work as they are accessing deprecated information within V10.

**To Reproduce**
1. Go to 'Enable short rest automation, attempt any of the three mentioned above'
2. Click on 'Short Rest button on sheet, then roll hit dice'
3. Check Console

**Expected behavior**
Expected to see an extra 1d6, 1d8, or an extra +1 hp per hit die to be applied.

**Screenshots**
![errorlog](https://user-images.githubusercontent.com/43119444/193155501-83670aaa-0654-420e-ae3c-49ba9d057282.png)
![chatlog](https://user-images.githubusercontent.com/43119444/193155550-921f3631-809c-4175-999f-ae4d20e698b3.png)
(Hp was at 1 which is why value became 8 after adding 7)
**Setup:**
 - Foundry Version: [v10.286]
 - System Version: [DND5e 2.0.3]
 - Rest Recovery Version: [v1.3.4]
 - Browser & version [Google Chrome 106.0.5249.62]

**Active modules:**
 - Rest Recovery
 - libwrapper
 -Module Management +

**Comment by Haxxer** [comment]
Could you please point out where the old DataModel is being used? There is no references to `.data.` anywhere in my code.

**Comment by Haxxer** [comment]
Actually, I found some stragglers - I'll patch this out in the upcoming update.

**Comment by Haxxer** [comment]
Fixed in 1.3.5
