### ISSUE TITLE
[Request] Implement "Sleeping In Armor" penalty also for medium armor.

### ISSUE THREAD

**Issue by tagnullde** [fantasycalendar/FoundryVTT-RestRecovery#98]
If I am not mistaken, the penalty from sleeping in armor applies also to medium armor.
However the module seems only to take heavy armor into account.

XGE:
"Sleeping in light armor has no adverse effect on the wearer, but sleeping in medium or heavy armor makes it difficult to recover fully during a long rest. When you finish a long rest during which you slept in medium or heavy armor, you regain only one quarter of your spent Hit Dice...pg. 77"

thx :)

**Comment by Haxxer** [comment]
Good catch, the original request only covered heavy armor, so that is what I implemented.

**Comment by tagnullde** [comment]
All good. :)

**Comment by Haxxer** [comment]
Done in latest update.
